
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Event'
export type * from './models/EventDetails'
export type * from './models/EventSlot'
export type * from './models/EventContact'
export type * from './models/Guests'
export type * from './models/Wishlist'
export type * from './models/WishlistClaim'
export type * from './commonInputTypes'