
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `EventSlot` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model EventSlot
 * 
 */
export type EventSlotModel = runtime.Types.Result.DefaultSelection<Prisma.$EventSlotPayload>

export type AggregateEventSlot = {
  _count: EventSlotCountAggregateOutputType | null
  _avg: EventSlotAvgAggregateOutputType | null
  _sum: EventSlotSumAggregateOutputType | null
  _min: EventSlotMinAggregateOutputType | null
  _max: EventSlotMaxAggregateOutputType | null
}

export type EventSlotAvgAggregateOutputType = {
  seats: number | null
}

export type EventSlotSumAggregateOutputType = {
  seats: number | null
}

export type EventSlotMinAggregateOutputType = {
  id: string | null
  start: Date | null
  end: Date | null
  seats: number | null
  eventId: string | null
}

export type EventSlotMaxAggregateOutputType = {
  id: string | null
  start: Date | null
  end: Date | null
  seats: number | null
  eventId: string | null
}

export type EventSlotCountAggregateOutputType = {
  id: number
  start: number
  end: number
  seats: number
  eventId: number
  _all: number
}


export type EventSlotAvgAggregateInputType = {
  seats?: true
}

export type EventSlotSumAggregateInputType = {
  seats?: true
}

export type EventSlotMinAggregateInputType = {
  id?: true
  start?: true
  end?: true
  seats?: true
  eventId?: true
}

export type EventSlotMaxAggregateInputType = {
  id?: true
  start?: true
  end?: true
  seats?: true
  eventId?: true
}

export type EventSlotCountAggregateInputType = {
  id?: true
  start?: true
  end?: true
  seats?: true
  eventId?: true
  _all?: true
}

export type EventSlotAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EventSlot to aggregate.
   */
  where?: Prisma.EventSlotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventSlots to fetch.
   */
  orderBy?: Prisma.EventSlotOrderByWithRelationInput | Prisma.EventSlotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EventSlotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventSlots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventSlots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned EventSlots
  **/
  _count?: true | EventSlotCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: EventSlotAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: EventSlotSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EventSlotMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EventSlotMaxAggregateInputType
}

export type GetEventSlotAggregateType<T extends EventSlotAggregateArgs> = {
      [P in keyof T & keyof AggregateEventSlot]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEventSlot[P]>
    : Prisma.GetScalarType<T[P], AggregateEventSlot[P]>
}




export type EventSlotGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EventSlotWhereInput
  orderBy?: Prisma.EventSlotOrderByWithAggregationInput | Prisma.EventSlotOrderByWithAggregationInput[]
  by: Prisma.EventSlotScalarFieldEnum[] | Prisma.EventSlotScalarFieldEnum
  having?: Prisma.EventSlotScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EventSlotCountAggregateInputType | true
  _avg?: EventSlotAvgAggregateInputType
  _sum?: EventSlotSumAggregateInputType
  _min?: EventSlotMinAggregateInputType
  _max?: EventSlotMaxAggregateInputType
}

export type EventSlotGroupByOutputType = {
  id: string
  start: Date
  end: Date
  seats: number
  eventId: string | null
  _count: EventSlotCountAggregateOutputType | null
  _avg: EventSlotAvgAggregateOutputType | null
  _sum: EventSlotSumAggregateOutputType | null
  _min: EventSlotMinAggregateOutputType | null
  _max: EventSlotMaxAggregateOutputType | null
}

export type GetEventSlotGroupByPayload<T extends EventSlotGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EventSlotGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EventSlotGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EventSlotGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EventSlotGroupByOutputType[P]>
      }
    >
  >



export type EventSlotWhereInput = {
  AND?: Prisma.EventSlotWhereInput | Prisma.EventSlotWhereInput[]
  OR?: Prisma.EventSlotWhereInput[]
  NOT?: Prisma.EventSlotWhereInput | Prisma.EventSlotWhereInput[]
  id?: Prisma.StringFilter<"EventSlot"> | string
  start?: Prisma.DateTimeFilter<"EventSlot"> | Date | string
  end?: Prisma.DateTimeFilter<"EventSlot"> | Date | string
  seats?: Prisma.IntFilter<"EventSlot"> | number
  eventId?: Prisma.StringNullableFilter<"EventSlot"> | string | null
  guests?: Prisma.GuestsListRelationFilter
  Event?: Prisma.XOR<Prisma.EventNullableScalarRelationFilter, Prisma.EventWhereInput> | null
}

export type EventSlotOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  start?: Prisma.SortOrder
  end?: Prisma.SortOrder
  seats?: Prisma.SortOrder
  eventId?: Prisma.SortOrderInput | Prisma.SortOrder
  guests?: Prisma.GuestsOrderByRelationAggregateInput
  Event?: Prisma.EventOrderByWithRelationInput
}

export type EventSlotWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.EventSlotWhereInput | Prisma.EventSlotWhereInput[]
  OR?: Prisma.EventSlotWhereInput[]
  NOT?: Prisma.EventSlotWhereInput | Prisma.EventSlotWhereInput[]
  start?: Prisma.DateTimeFilter<"EventSlot"> | Date | string
  end?: Prisma.DateTimeFilter<"EventSlot"> | Date | string
  seats?: Prisma.IntFilter<"EventSlot"> | number
  eventId?: Prisma.StringNullableFilter<"EventSlot"> | string | null
  guests?: Prisma.GuestsListRelationFilter
  Event?: Prisma.XOR<Prisma.EventNullableScalarRelationFilter, Prisma.EventWhereInput> | null
}, "id">

export type EventSlotOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  start?: Prisma.SortOrder
  end?: Prisma.SortOrder
  seats?: Prisma.SortOrder
  eventId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.EventSlotCountOrderByAggregateInput
  _avg?: Prisma.EventSlotAvgOrderByAggregateInput
  _max?: Prisma.EventSlotMaxOrderByAggregateInput
  _min?: Prisma.EventSlotMinOrderByAggregateInput
  _sum?: Prisma.EventSlotSumOrderByAggregateInput
}

export type EventSlotScalarWhereWithAggregatesInput = {
  AND?: Prisma.EventSlotScalarWhereWithAggregatesInput | Prisma.EventSlotScalarWhereWithAggregatesInput[]
  OR?: Prisma.EventSlotScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EventSlotScalarWhereWithAggregatesInput | Prisma.EventSlotScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"EventSlot"> | string
  start?: Prisma.DateTimeWithAggregatesFilter<"EventSlot"> | Date | string
  end?: Prisma.DateTimeWithAggregatesFilter<"EventSlot"> | Date | string
  seats?: Prisma.IntWithAggregatesFilter<"EventSlot"> | number
  eventId?: Prisma.StringNullableWithAggregatesFilter<"EventSlot"> | string | null
}

export type EventSlotCreateInput = {
  id?: string
  start: Date | string
  end: Date | string
  seats: number
  guests?: Prisma.GuestsCreateNestedManyWithoutReservationInput
  Event?: Prisma.EventCreateNestedOneWithoutSlotsInput
}

export type EventSlotUncheckedCreateInput = {
  id?: string
  start: Date | string
  end: Date | string
  seats: number
  eventId?: string | null
  guests?: Prisma.GuestsUncheckedCreateNestedManyWithoutReservationInput
}

export type EventSlotUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  start?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seats?: Prisma.IntFieldUpdateOperationsInput | number
  guests?: Prisma.GuestsUpdateManyWithoutReservationNestedInput
  Event?: Prisma.EventUpdateOneWithoutSlotsNestedInput
}

export type EventSlotUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  start?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seats?: Prisma.IntFieldUpdateOperationsInput | number
  eventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  guests?: Prisma.GuestsUncheckedUpdateManyWithoutReservationNestedInput
}

export type EventSlotCreateManyInput = {
  id?: string
  start: Date | string
  end: Date | string
  seats: number
  eventId?: string | null
}

export type EventSlotUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  start?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seats?: Prisma.IntFieldUpdateOperationsInput | number
}

export type EventSlotUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  start?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seats?: Prisma.IntFieldUpdateOperationsInput | number
  eventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type EventSlotListRelationFilter = {
  every?: Prisma.EventSlotWhereInput
  some?: Prisma.EventSlotWhereInput
  none?: Prisma.EventSlotWhereInput
}

export type EventSlotOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EventSlotCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  start?: Prisma.SortOrder
  end?: Prisma.SortOrder
  seats?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
}

export type EventSlotAvgOrderByAggregateInput = {
  seats?: Prisma.SortOrder
}

export type EventSlotMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  start?: Prisma.SortOrder
  end?: Prisma.SortOrder
  seats?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
}

export type EventSlotMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  start?: Prisma.SortOrder
  end?: Prisma.SortOrder
  seats?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
}

export type EventSlotSumOrderByAggregateInput = {
  seats?: Prisma.SortOrder
}

export type EventSlotScalarRelationFilter = {
  is?: Prisma.EventSlotWhereInput
  isNot?: Prisma.EventSlotWhereInput
}

export type EventSlotCreateNestedManyWithoutEventInput = {
  create?: Prisma.XOR<Prisma.EventSlotCreateWithoutEventInput, Prisma.EventSlotUncheckedCreateWithoutEventInput> | Prisma.EventSlotCreateWithoutEventInput[] | Prisma.EventSlotUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventSlotCreateOrConnectWithoutEventInput | Prisma.EventSlotCreateOrConnectWithoutEventInput[]
  createMany?: Prisma.EventSlotCreateManyEventInputEnvelope
  connect?: Prisma.EventSlotWhereUniqueInput | Prisma.EventSlotWhereUniqueInput[]
}

export type EventSlotUncheckedCreateNestedManyWithoutEventInput = {
  create?: Prisma.XOR<Prisma.EventSlotCreateWithoutEventInput, Prisma.EventSlotUncheckedCreateWithoutEventInput> | Prisma.EventSlotCreateWithoutEventInput[] | Prisma.EventSlotUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventSlotCreateOrConnectWithoutEventInput | Prisma.EventSlotCreateOrConnectWithoutEventInput[]
  createMany?: Prisma.EventSlotCreateManyEventInputEnvelope
  connect?: Prisma.EventSlotWhereUniqueInput | Prisma.EventSlotWhereUniqueInput[]
}

export type EventSlotUpdateManyWithoutEventNestedInput = {
  create?: Prisma.XOR<Prisma.EventSlotCreateWithoutEventInput, Prisma.EventSlotUncheckedCreateWithoutEventInput> | Prisma.EventSlotCreateWithoutEventInput[] | Prisma.EventSlotUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventSlotCreateOrConnectWithoutEventInput | Prisma.EventSlotCreateOrConnectWithoutEventInput[]
  upsert?: Prisma.EventSlotUpsertWithWhereUniqueWithoutEventInput | Prisma.EventSlotUpsertWithWhereUniqueWithoutEventInput[]
  createMany?: Prisma.EventSlotCreateManyEventInputEnvelope
  set?: Prisma.EventSlotWhereUniqueInput | Prisma.EventSlotWhereUniqueInput[]
  disconnect?: Prisma.EventSlotWhereUniqueInput | Prisma.EventSlotWhereUniqueInput[]
  delete?: Prisma.EventSlotWhereUniqueInput | Prisma.EventSlotWhereUniqueInput[]
  connect?: Prisma.EventSlotWhereUniqueInput | Prisma.EventSlotWhereUniqueInput[]
  update?: Prisma.EventSlotUpdateWithWhereUniqueWithoutEventInput | Prisma.EventSlotUpdateWithWhereUniqueWithoutEventInput[]
  updateMany?: Prisma.EventSlotUpdateManyWithWhereWithoutEventInput | Prisma.EventSlotUpdateManyWithWhereWithoutEventInput[]
  deleteMany?: Prisma.EventSlotScalarWhereInput | Prisma.EventSlotScalarWhereInput[]
}

export type EventSlotUncheckedUpdateManyWithoutEventNestedInput = {
  create?: Prisma.XOR<Prisma.EventSlotCreateWithoutEventInput, Prisma.EventSlotUncheckedCreateWithoutEventInput> | Prisma.EventSlotCreateWithoutEventInput[] | Prisma.EventSlotUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventSlotCreateOrConnectWithoutEventInput | Prisma.EventSlotCreateOrConnectWithoutEventInput[]
  upsert?: Prisma.EventSlotUpsertWithWhereUniqueWithoutEventInput | Prisma.EventSlotUpsertWithWhereUniqueWithoutEventInput[]
  createMany?: Prisma.EventSlotCreateManyEventInputEnvelope
  set?: Prisma.EventSlotWhereUniqueInput | Prisma.EventSlotWhereUniqueInput[]
  disconnect?: Prisma.EventSlotWhereUniqueInput | Prisma.EventSlotWhereUniqueInput[]
  delete?: Prisma.EventSlotWhereUniqueInput | Prisma.EventSlotWhereUniqueInput[]
  connect?: Prisma.EventSlotWhereUniqueInput | Prisma.EventSlotWhereUniqueInput[]
  update?: Prisma.EventSlotUpdateWithWhereUniqueWithoutEventInput | Prisma.EventSlotUpdateWithWhereUniqueWithoutEventInput[]
  updateMany?: Prisma.EventSlotUpdateManyWithWhereWithoutEventInput | Prisma.EventSlotUpdateManyWithWhereWithoutEventInput[]
  deleteMany?: Prisma.EventSlotScalarWhereInput | Prisma.EventSlotScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type EventSlotCreateNestedOneWithoutGuestsInput = {
  create?: Prisma.XOR<Prisma.EventSlotCreateWithoutGuestsInput, Prisma.EventSlotUncheckedCreateWithoutGuestsInput>
  connectOrCreate?: Prisma.EventSlotCreateOrConnectWithoutGuestsInput
  connect?: Prisma.EventSlotWhereUniqueInput
}

export type EventSlotUpdateOneRequiredWithoutGuestsNestedInput = {
  create?: Prisma.XOR<Prisma.EventSlotCreateWithoutGuestsInput, Prisma.EventSlotUncheckedCreateWithoutGuestsInput>
  connectOrCreate?: Prisma.EventSlotCreateOrConnectWithoutGuestsInput
  upsert?: Prisma.EventSlotUpsertWithoutGuestsInput
  connect?: Prisma.EventSlotWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.EventSlotUpdateToOneWithWhereWithoutGuestsInput, Prisma.EventSlotUpdateWithoutGuestsInput>, Prisma.EventSlotUncheckedUpdateWithoutGuestsInput>
}

export type EventSlotCreateWithoutEventInput = {
  id?: string
  start: Date | string
  end: Date | string
  seats: number
  guests?: Prisma.GuestsCreateNestedManyWithoutReservationInput
}

export type EventSlotUncheckedCreateWithoutEventInput = {
  id?: string
  start: Date | string
  end: Date | string
  seats: number
  guests?: Prisma.GuestsUncheckedCreateNestedManyWithoutReservationInput
}

export type EventSlotCreateOrConnectWithoutEventInput = {
  where: Prisma.EventSlotWhereUniqueInput
  create: Prisma.XOR<Prisma.EventSlotCreateWithoutEventInput, Prisma.EventSlotUncheckedCreateWithoutEventInput>
}

export type EventSlotCreateManyEventInputEnvelope = {
  data: Prisma.EventSlotCreateManyEventInput | Prisma.EventSlotCreateManyEventInput[]
}

export type EventSlotUpsertWithWhereUniqueWithoutEventInput = {
  where: Prisma.EventSlotWhereUniqueInput
  update: Prisma.XOR<Prisma.EventSlotUpdateWithoutEventInput, Prisma.EventSlotUncheckedUpdateWithoutEventInput>
  create: Prisma.XOR<Prisma.EventSlotCreateWithoutEventInput, Prisma.EventSlotUncheckedCreateWithoutEventInput>
}

export type EventSlotUpdateWithWhereUniqueWithoutEventInput = {
  where: Prisma.EventSlotWhereUniqueInput
  data: Prisma.XOR<Prisma.EventSlotUpdateWithoutEventInput, Prisma.EventSlotUncheckedUpdateWithoutEventInput>
}

export type EventSlotUpdateManyWithWhereWithoutEventInput = {
  where: Prisma.EventSlotScalarWhereInput
  data: Prisma.XOR<Prisma.EventSlotUpdateManyMutationInput, Prisma.EventSlotUncheckedUpdateManyWithoutEventInput>
}

export type EventSlotScalarWhereInput = {
  AND?: Prisma.EventSlotScalarWhereInput | Prisma.EventSlotScalarWhereInput[]
  OR?: Prisma.EventSlotScalarWhereInput[]
  NOT?: Prisma.EventSlotScalarWhereInput | Prisma.EventSlotScalarWhereInput[]
  id?: Prisma.StringFilter<"EventSlot"> | string
  start?: Prisma.DateTimeFilter<"EventSlot"> | Date | string
  end?: Prisma.DateTimeFilter<"EventSlot"> | Date | string
  seats?: Prisma.IntFilter<"EventSlot"> | number
  eventId?: Prisma.StringNullableFilter<"EventSlot"> | string | null
}

export type EventSlotCreateWithoutGuestsInput = {
  id?: string
  start: Date | string
  end: Date | string
  seats: number
  Event?: Prisma.EventCreateNestedOneWithoutSlotsInput
}

export type EventSlotUncheckedCreateWithoutGuestsInput = {
  id?: string
  start: Date | string
  end: Date | string
  seats: number
  eventId?: string | null
}

export type EventSlotCreateOrConnectWithoutGuestsInput = {
  where: Prisma.EventSlotWhereUniqueInput
  create: Prisma.XOR<Prisma.EventSlotCreateWithoutGuestsInput, Prisma.EventSlotUncheckedCreateWithoutGuestsInput>
}

export type EventSlotUpsertWithoutGuestsInput = {
  update: Prisma.XOR<Prisma.EventSlotUpdateWithoutGuestsInput, Prisma.EventSlotUncheckedUpdateWithoutGuestsInput>
  create: Prisma.XOR<Prisma.EventSlotCreateWithoutGuestsInput, Prisma.EventSlotUncheckedCreateWithoutGuestsInput>
  where?: Prisma.EventSlotWhereInput
}

export type EventSlotUpdateToOneWithWhereWithoutGuestsInput = {
  where?: Prisma.EventSlotWhereInput
  data: Prisma.XOR<Prisma.EventSlotUpdateWithoutGuestsInput, Prisma.EventSlotUncheckedUpdateWithoutGuestsInput>
}

export type EventSlotUpdateWithoutGuestsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  start?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seats?: Prisma.IntFieldUpdateOperationsInput | number
  Event?: Prisma.EventUpdateOneWithoutSlotsNestedInput
}

export type EventSlotUncheckedUpdateWithoutGuestsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  start?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seats?: Prisma.IntFieldUpdateOperationsInput | number
  eventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type EventSlotCreateManyEventInput = {
  id?: string
  start: Date | string
  end: Date | string
  seats: number
}

export type EventSlotUpdateWithoutEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  start?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seats?: Prisma.IntFieldUpdateOperationsInput | number
  guests?: Prisma.GuestsUpdateManyWithoutReservationNestedInput
}

export type EventSlotUncheckedUpdateWithoutEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  start?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seats?: Prisma.IntFieldUpdateOperationsInput | number
  guests?: Prisma.GuestsUncheckedUpdateManyWithoutReservationNestedInput
}

export type EventSlotUncheckedUpdateManyWithoutEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  start?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seats?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type EventSlotCountOutputType
 */

export type EventSlotCountOutputType = {
  guests: number
}

export type EventSlotCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  guests?: boolean | EventSlotCountOutputTypeCountGuestsArgs
}

/**
 * EventSlotCountOutputType without action
 */
export type EventSlotCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventSlotCountOutputType
   */
  select?: Prisma.EventSlotCountOutputTypeSelect<ExtArgs> | null
}

/**
 * EventSlotCountOutputType without action
 */
export type EventSlotCountOutputTypeCountGuestsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GuestsWhereInput
}


export type EventSlotSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  start?: boolean
  end?: boolean
  seats?: boolean
  eventId?: boolean
  guests?: boolean | Prisma.EventSlot$guestsArgs<ExtArgs>
  Event?: boolean | Prisma.EventSlot$EventArgs<ExtArgs>
  _count?: boolean | Prisma.EventSlotCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventSlot"]>

export type EventSlotSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  start?: boolean
  end?: boolean
  seats?: boolean
  eventId?: boolean
  Event?: boolean | Prisma.EventSlot$EventArgs<ExtArgs>
}, ExtArgs["result"]["eventSlot"]>

export type EventSlotSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  start?: boolean
  end?: boolean
  seats?: boolean
  eventId?: boolean
  Event?: boolean | Prisma.EventSlot$EventArgs<ExtArgs>
}, ExtArgs["result"]["eventSlot"]>

export type EventSlotSelectScalar = {
  id?: boolean
  start?: boolean
  end?: boolean
  seats?: boolean
  eventId?: boolean
}

export type EventSlotOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "start" | "end" | "seats" | "eventId", ExtArgs["result"]["eventSlot"]>
export type EventSlotInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  guests?: boolean | Prisma.EventSlot$guestsArgs<ExtArgs>
  Event?: boolean | Prisma.EventSlot$EventArgs<ExtArgs>
  _count?: boolean | Prisma.EventSlotCountOutputTypeDefaultArgs<ExtArgs>
}
export type EventSlotIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Event?: boolean | Prisma.EventSlot$EventArgs<ExtArgs>
}
export type EventSlotIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Event?: boolean | Prisma.EventSlot$EventArgs<ExtArgs>
}

export type $EventSlotPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "EventSlot"
  objects: {
    guests: Prisma.$GuestsPayload<ExtArgs>[]
    Event: Prisma.$EventPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    start: Date
    end: Date
    seats: number
    eventId: string | null
  }, ExtArgs["result"]["eventSlot"]>
  composites: {}
}

export type EventSlotGetPayload<S extends boolean | null | undefined | EventSlotDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EventSlotPayload, S>

export type EventSlotCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EventSlotFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EventSlotCountAggregateInputType | true
  }

export interface EventSlotDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['EventSlot'], meta: { name: 'EventSlot' } }
  /**
   * Find zero or one EventSlot that matches the filter.
   * @param {EventSlotFindUniqueArgs} args - Arguments to find a EventSlot
   * @example
   * // Get one EventSlot
   * const eventSlot = await prisma.eventSlot.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EventSlotFindUniqueArgs>(args: Prisma.SelectSubset<T, EventSlotFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EventSlotClient<runtime.Types.Result.GetResult<Prisma.$EventSlotPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one EventSlot that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EventSlotFindUniqueOrThrowArgs} args - Arguments to find a EventSlot
   * @example
   * // Get one EventSlot
   * const eventSlot = await prisma.eventSlot.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EventSlotFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EventSlotFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EventSlotClient<runtime.Types.Result.GetResult<Prisma.$EventSlotPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EventSlot that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventSlotFindFirstArgs} args - Arguments to find a EventSlot
   * @example
   * // Get one EventSlot
   * const eventSlot = await prisma.eventSlot.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EventSlotFindFirstArgs>(args?: Prisma.SelectSubset<T, EventSlotFindFirstArgs<ExtArgs>>): Prisma.Prisma__EventSlotClient<runtime.Types.Result.GetResult<Prisma.$EventSlotPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EventSlot that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventSlotFindFirstOrThrowArgs} args - Arguments to find a EventSlot
   * @example
   * // Get one EventSlot
   * const eventSlot = await prisma.eventSlot.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EventSlotFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EventSlotFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EventSlotClient<runtime.Types.Result.GetResult<Prisma.$EventSlotPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more EventSlots that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventSlotFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all EventSlots
   * const eventSlots = await prisma.eventSlot.findMany()
   * 
   * // Get first 10 EventSlots
   * const eventSlots = await prisma.eventSlot.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const eventSlotWithIdOnly = await prisma.eventSlot.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EventSlotFindManyArgs>(args?: Prisma.SelectSubset<T, EventSlotFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventSlotPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a EventSlot.
   * @param {EventSlotCreateArgs} args - Arguments to create a EventSlot.
   * @example
   * // Create one EventSlot
   * const EventSlot = await prisma.eventSlot.create({
   *   data: {
   *     // ... data to create a EventSlot
   *   }
   * })
   * 
   */
  create<T extends EventSlotCreateArgs>(args: Prisma.SelectSubset<T, EventSlotCreateArgs<ExtArgs>>): Prisma.Prisma__EventSlotClient<runtime.Types.Result.GetResult<Prisma.$EventSlotPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many EventSlots.
   * @param {EventSlotCreateManyArgs} args - Arguments to create many EventSlots.
   * @example
   * // Create many EventSlots
   * const eventSlot = await prisma.eventSlot.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EventSlotCreateManyArgs>(args?: Prisma.SelectSubset<T, EventSlotCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many EventSlots and returns the data saved in the database.
   * @param {EventSlotCreateManyAndReturnArgs} args - Arguments to create many EventSlots.
   * @example
   * // Create many EventSlots
   * const eventSlot = await prisma.eventSlot.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many EventSlots and only return the `id`
   * const eventSlotWithIdOnly = await prisma.eventSlot.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EventSlotCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EventSlotCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventSlotPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a EventSlot.
   * @param {EventSlotDeleteArgs} args - Arguments to delete one EventSlot.
   * @example
   * // Delete one EventSlot
   * const EventSlot = await prisma.eventSlot.delete({
   *   where: {
   *     // ... filter to delete one EventSlot
   *   }
   * })
   * 
   */
  delete<T extends EventSlotDeleteArgs>(args: Prisma.SelectSubset<T, EventSlotDeleteArgs<ExtArgs>>): Prisma.Prisma__EventSlotClient<runtime.Types.Result.GetResult<Prisma.$EventSlotPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one EventSlot.
   * @param {EventSlotUpdateArgs} args - Arguments to update one EventSlot.
   * @example
   * // Update one EventSlot
   * const eventSlot = await prisma.eventSlot.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EventSlotUpdateArgs>(args: Prisma.SelectSubset<T, EventSlotUpdateArgs<ExtArgs>>): Prisma.Prisma__EventSlotClient<runtime.Types.Result.GetResult<Prisma.$EventSlotPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more EventSlots.
   * @param {EventSlotDeleteManyArgs} args - Arguments to filter EventSlots to delete.
   * @example
   * // Delete a few EventSlots
   * const { count } = await prisma.eventSlot.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EventSlotDeleteManyArgs>(args?: Prisma.SelectSubset<T, EventSlotDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EventSlots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventSlotUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many EventSlots
   * const eventSlot = await prisma.eventSlot.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EventSlotUpdateManyArgs>(args: Prisma.SelectSubset<T, EventSlotUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EventSlots and returns the data updated in the database.
   * @param {EventSlotUpdateManyAndReturnArgs} args - Arguments to update many EventSlots.
   * @example
   * // Update many EventSlots
   * const eventSlot = await prisma.eventSlot.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more EventSlots and only return the `id`
   * const eventSlotWithIdOnly = await prisma.eventSlot.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EventSlotUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EventSlotUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventSlotPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one EventSlot.
   * @param {EventSlotUpsertArgs} args - Arguments to update or create a EventSlot.
   * @example
   * // Update or create a EventSlot
   * const eventSlot = await prisma.eventSlot.upsert({
   *   create: {
   *     // ... data to create a EventSlot
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the EventSlot we want to update
   *   }
   * })
   */
  upsert<T extends EventSlotUpsertArgs>(args: Prisma.SelectSubset<T, EventSlotUpsertArgs<ExtArgs>>): Prisma.Prisma__EventSlotClient<runtime.Types.Result.GetResult<Prisma.$EventSlotPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of EventSlots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventSlotCountArgs} args - Arguments to filter EventSlots to count.
   * @example
   * // Count the number of EventSlots
   * const count = await prisma.eventSlot.count({
   *   where: {
   *     // ... the filter for the EventSlots we want to count
   *   }
   * })
  **/
  count<T extends EventSlotCountArgs>(
    args?: Prisma.Subset<T, EventSlotCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EventSlotCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a EventSlot.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventSlotAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EventSlotAggregateArgs>(args: Prisma.Subset<T, EventSlotAggregateArgs>): Prisma.PrismaPromise<GetEventSlotAggregateType<T>>

  /**
   * Group by EventSlot.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventSlotGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EventSlotGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EventSlotGroupByArgs['orderBy'] }
      : { orderBy?: EventSlotGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EventSlotGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEventSlotGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the EventSlot model
 */
readonly fields: EventSlotFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for EventSlot.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EventSlotClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  guests<T extends Prisma.EventSlot$guestsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EventSlot$guestsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GuestsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  Event<T extends Prisma.EventSlot$EventArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EventSlot$EventArgs<ExtArgs>>): Prisma.Prisma__EventClient<runtime.Types.Result.GetResult<Prisma.$EventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the EventSlot model
 */
export interface EventSlotFieldRefs {
  readonly id: Prisma.FieldRef<"EventSlot", 'String'>
  readonly start: Prisma.FieldRef<"EventSlot", 'DateTime'>
  readonly end: Prisma.FieldRef<"EventSlot", 'DateTime'>
  readonly seats: Prisma.FieldRef<"EventSlot", 'Int'>
  readonly eventId: Prisma.FieldRef<"EventSlot", 'String'>
}
    

// Custom InputTypes
/**
 * EventSlot findUnique
 */
export type EventSlotFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventSlot
   */
  select?: Prisma.EventSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventSlot
   */
  omit?: Prisma.EventSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventSlotInclude<ExtArgs> | null
  /**
   * Filter, which EventSlot to fetch.
   */
  where: Prisma.EventSlotWhereUniqueInput
}

/**
 * EventSlot findUniqueOrThrow
 */
export type EventSlotFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventSlot
   */
  select?: Prisma.EventSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventSlot
   */
  omit?: Prisma.EventSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventSlotInclude<ExtArgs> | null
  /**
   * Filter, which EventSlot to fetch.
   */
  where: Prisma.EventSlotWhereUniqueInput
}

/**
 * EventSlot findFirst
 */
export type EventSlotFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventSlot
   */
  select?: Prisma.EventSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventSlot
   */
  omit?: Prisma.EventSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventSlotInclude<ExtArgs> | null
  /**
   * Filter, which EventSlot to fetch.
   */
  where?: Prisma.EventSlotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventSlots to fetch.
   */
  orderBy?: Prisma.EventSlotOrderByWithRelationInput | Prisma.EventSlotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EventSlots.
   */
  cursor?: Prisma.EventSlotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventSlots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventSlots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventSlots.
   */
  distinct?: Prisma.EventSlotScalarFieldEnum | Prisma.EventSlotScalarFieldEnum[]
}

/**
 * EventSlot findFirstOrThrow
 */
export type EventSlotFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventSlot
   */
  select?: Prisma.EventSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventSlot
   */
  omit?: Prisma.EventSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventSlotInclude<ExtArgs> | null
  /**
   * Filter, which EventSlot to fetch.
   */
  where?: Prisma.EventSlotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventSlots to fetch.
   */
  orderBy?: Prisma.EventSlotOrderByWithRelationInput | Prisma.EventSlotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EventSlots.
   */
  cursor?: Prisma.EventSlotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventSlots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventSlots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventSlots.
   */
  distinct?: Prisma.EventSlotScalarFieldEnum | Prisma.EventSlotScalarFieldEnum[]
}

/**
 * EventSlot findMany
 */
export type EventSlotFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventSlot
   */
  select?: Prisma.EventSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventSlot
   */
  omit?: Prisma.EventSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventSlotInclude<ExtArgs> | null
  /**
   * Filter, which EventSlots to fetch.
   */
  where?: Prisma.EventSlotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventSlots to fetch.
   */
  orderBy?: Prisma.EventSlotOrderByWithRelationInput | Prisma.EventSlotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing EventSlots.
   */
  cursor?: Prisma.EventSlotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventSlots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventSlots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventSlots.
   */
  distinct?: Prisma.EventSlotScalarFieldEnum | Prisma.EventSlotScalarFieldEnum[]
}

/**
 * EventSlot create
 */
export type EventSlotCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventSlot
   */
  select?: Prisma.EventSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventSlot
   */
  omit?: Prisma.EventSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventSlotInclude<ExtArgs> | null
  /**
   * The data needed to create a EventSlot.
   */
  data: Prisma.XOR<Prisma.EventSlotCreateInput, Prisma.EventSlotUncheckedCreateInput>
}

/**
 * EventSlot createMany
 */
export type EventSlotCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many EventSlots.
   */
  data: Prisma.EventSlotCreateManyInput | Prisma.EventSlotCreateManyInput[]
}

/**
 * EventSlot createManyAndReturn
 */
export type EventSlotCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventSlot
   */
  select?: Prisma.EventSlotSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EventSlot
   */
  omit?: Prisma.EventSlotOmit<ExtArgs> | null
  /**
   * The data used to create many EventSlots.
   */
  data: Prisma.EventSlotCreateManyInput | Prisma.EventSlotCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventSlotIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * EventSlot update
 */
export type EventSlotUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventSlot
   */
  select?: Prisma.EventSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventSlot
   */
  omit?: Prisma.EventSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventSlotInclude<ExtArgs> | null
  /**
   * The data needed to update a EventSlot.
   */
  data: Prisma.XOR<Prisma.EventSlotUpdateInput, Prisma.EventSlotUncheckedUpdateInput>
  /**
   * Choose, which EventSlot to update.
   */
  where: Prisma.EventSlotWhereUniqueInput
}

/**
 * EventSlot updateMany
 */
export type EventSlotUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update EventSlots.
   */
  data: Prisma.XOR<Prisma.EventSlotUpdateManyMutationInput, Prisma.EventSlotUncheckedUpdateManyInput>
  /**
   * Filter which EventSlots to update
   */
  where?: Prisma.EventSlotWhereInput
  /**
   * Limit how many EventSlots to update.
   */
  limit?: number
}

/**
 * EventSlot updateManyAndReturn
 */
export type EventSlotUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventSlot
   */
  select?: Prisma.EventSlotSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EventSlot
   */
  omit?: Prisma.EventSlotOmit<ExtArgs> | null
  /**
   * The data used to update EventSlots.
   */
  data: Prisma.XOR<Prisma.EventSlotUpdateManyMutationInput, Prisma.EventSlotUncheckedUpdateManyInput>
  /**
   * Filter which EventSlots to update
   */
  where?: Prisma.EventSlotWhereInput
  /**
   * Limit how many EventSlots to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventSlotIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * EventSlot upsert
 */
export type EventSlotUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventSlot
   */
  select?: Prisma.EventSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventSlot
   */
  omit?: Prisma.EventSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventSlotInclude<ExtArgs> | null
  /**
   * The filter to search for the EventSlot to update in case it exists.
   */
  where: Prisma.EventSlotWhereUniqueInput
  /**
   * In case the EventSlot found by the `where` argument doesn't exist, create a new EventSlot with this data.
   */
  create: Prisma.XOR<Prisma.EventSlotCreateInput, Prisma.EventSlotUncheckedCreateInput>
  /**
   * In case the EventSlot was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EventSlotUpdateInput, Prisma.EventSlotUncheckedUpdateInput>
}

/**
 * EventSlot delete
 */
export type EventSlotDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventSlot
   */
  select?: Prisma.EventSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventSlot
   */
  omit?: Prisma.EventSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventSlotInclude<ExtArgs> | null
  /**
   * Filter which EventSlot to delete.
   */
  where: Prisma.EventSlotWhereUniqueInput
}

/**
 * EventSlot deleteMany
 */
export type EventSlotDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EventSlots to delete
   */
  where?: Prisma.EventSlotWhereInput
  /**
   * Limit how many EventSlots to delete.
   */
  limit?: number
}

/**
 * EventSlot.guests
 */
export type EventSlot$guestsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Guests
   */
  select?: Prisma.GuestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Guests
   */
  omit?: Prisma.GuestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuestsInclude<ExtArgs> | null
  where?: Prisma.GuestsWhereInput
  orderBy?: Prisma.GuestsOrderByWithRelationInput | Prisma.GuestsOrderByWithRelationInput[]
  cursor?: Prisma.GuestsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.GuestsScalarFieldEnum | Prisma.GuestsScalarFieldEnum[]
}

/**
 * EventSlot.Event
 */
export type EventSlot$EventArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Event
   */
  select?: Prisma.EventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Event
   */
  omit?: Prisma.EventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventInclude<ExtArgs> | null
  where?: Prisma.EventWhereInput
}

/**
 * EventSlot without action
 */
export type EventSlotDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventSlot
   */
  select?: Prisma.EventSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventSlot
   */
  omit?: Prisma.EventSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventSlotInclude<ExtArgs> | null
}
