
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `EventContact` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model EventContact
 * 
 */
export type EventContactModel = runtime.Types.Result.DefaultSelection<Prisma.$EventContactPayload>

export type AggregateEventContact = {
  _count: EventContactCountAggregateOutputType | null
  _min: EventContactMinAggregateOutputType | null
  _max: EventContactMaxAggregateOutputType | null
}

export type EventContactMinAggregateOutputType = {
  id: string | null
  name: string | null
  email: string | null
  phone: string | null
  message: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type EventContactMaxAggregateOutputType = {
  id: string | null
  name: string | null
  email: string | null
  phone: string | null
  message: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type EventContactCountAggregateOutputType = {
  id: number
  name: number
  email: number
  phone: number
  message: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  _all: number
}


export type EventContactMinAggregateInputType = {
  id?: true
  name?: true
  email?: true
  phone?: true
  message?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type EventContactMaxAggregateInputType = {
  id?: true
  name?: true
  email?: true
  phone?: true
  message?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type EventContactCountAggregateInputType = {
  id?: true
  name?: true
  email?: true
  phone?: true
  message?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  _all?: true
}

export type EventContactAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EventContact to aggregate.
   */
  where?: Prisma.EventContactWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventContacts to fetch.
   */
  orderBy?: Prisma.EventContactOrderByWithRelationInput | Prisma.EventContactOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EventContactWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventContacts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventContacts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned EventContacts
  **/
  _count?: true | EventContactCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EventContactMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EventContactMaxAggregateInputType
}

export type GetEventContactAggregateType<T extends EventContactAggregateArgs> = {
      [P in keyof T & keyof AggregateEventContact]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEventContact[P]>
    : Prisma.GetScalarType<T[P], AggregateEventContact[P]>
}




export type EventContactGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EventContactWhereInput
  orderBy?: Prisma.EventContactOrderByWithAggregationInput | Prisma.EventContactOrderByWithAggregationInput[]
  by: Prisma.EventContactScalarFieldEnum[] | Prisma.EventContactScalarFieldEnum
  having?: Prisma.EventContactScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EventContactCountAggregateInputType | true
  _min?: EventContactMinAggregateInputType
  _max?: EventContactMaxAggregateInputType
}

export type EventContactGroupByOutputType = {
  id: string
  name: string
  email: string | null
  phone: string | null
  message: string | null
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  _count: EventContactCountAggregateOutputType | null
  _min: EventContactMinAggregateOutputType | null
  _max: EventContactMaxAggregateOutputType | null
}

export type GetEventContactGroupByPayload<T extends EventContactGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EventContactGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EventContactGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EventContactGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EventContactGroupByOutputType[P]>
      }
    >
  >



export type EventContactWhereInput = {
  AND?: Prisma.EventContactWhereInput | Prisma.EventContactWhereInput[]
  OR?: Prisma.EventContactWhereInput[]
  NOT?: Prisma.EventContactWhereInput | Prisma.EventContactWhereInput[]
  id?: Prisma.StringFilter<"EventContact"> | string
  name?: Prisma.StringFilter<"EventContact"> | string
  email?: Prisma.StringNullableFilter<"EventContact"> | string | null
  phone?: Prisma.StringNullableFilter<"EventContact"> | string | null
  message?: Prisma.StringNullableFilter<"EventContact"> | string | null
  createdAt?: Prisma.DateTimeFilter<"EventContact"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EventContact"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"EventContact"> | Date | string | null
  event?: Prisma.XOR<Prisma.EventDetailsScalarRelationFilter, Prisma.EventDetailsWhereInput>
}

export type EventContactOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  phone?: Prisma.SortOrderInput | Prisma.SortOrder
  message?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  event?: Prisma.EventDetailsOrderByWithRelationInput
}

export type EventContactWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.EventContactWhereInput | Prisma.EventContactWhereInput[]
  OR?: Prisma.EventContactWhereInput[]
  NOT?: Prisma.EventContactWhereInput | Prisma.EventContactWhereInput[]
  name?: Prisma.StringFilter<"EventContact"> | string
  email?: Prisma.StringNullableFilter<"EventContact"> | string | null
  phone?: Prisma.StringNullableFilter<"EventContact"> | string | null
  message?: Prisma.StringNullableFilter<"EventContact"> | string | null
  createdAt?: Prisma.DateTimeFilter<"EventContact"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EventContact"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"EventContact"> | Date | string | null
  event?: Prisma.XOR<Prisma.EventDetailsScalarRelationFilter, Prisma.EventDetailsWhereInput>
}, "id">

export type EventContactOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  phone?: Prisma.SortOrderInput | Prisma.SortOrder
  message?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.EventContactCountOrderByAggregateInput
  _max?: Prisma.EventContactMaxOrderByAggregateInput
  _min?: Prisma.EventContactMinOrderByAggregateInput
}

export type EventContactScalarWhereWithAggregatesInput = {
  AND?: Prisma.EventContactScalarWhereWithAggregatesInput | Prisma.EventContactScalarWhereWithAggregatesInput[]
  OR?: Prisma.EventContactScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EventContactScalarWhereWithAggregatesInput | Prisma.EventContactScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"EventContact"> | string
  name?: Prisma.StringWithAggregatesFilter<"EventContact"> | string
  email?: Prisma.StringNullableWithAggregatesFilter<"EventContact"> | string | null
  phone?: Prisma.StringNullableWithAggregatesFilter<"EventContact"> | string | null
  message?: Prisma.StringNullableWithAggregatesFilter<"EventContact"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"EventContact"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"EventContact"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"EventContact"> | Date | string | null
}

export type EventContactCreateInput = {
  name: string
  email?: string | null
  phone?: string | null
  message?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  event?: Prisma.EventDetailsCreateNestedOneWithoutContactInput
}

export type EventContactUncheckedCreateInput = {
  id?: string
  name: string
  email?: string | null
  phone?: string | null
  message?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type EventContactUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  event?: Prisma.EventDetailsUpdateOneRequiredWithoutContactNestedInput
}

export type EventContactUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EventContactCreateManyInput = {
  id?: string
  name: string
  email?: string | null
  phone?: string | null
  message?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type EventContactUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EventContactUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EventContactNullableScalarRelationFilter = {
  is?: Prisma.EventContactWhereInput | null
  isNot?: Prisma.EventContactWhereInput | null
}

export type EventContactCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  message?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type EventContactMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  message?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type EventContactMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  message?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type EventContactCreateNestedOneWithoutEventInput = {
  create?: Prisma.XOR<Prisma.EventContactCreateWithoutEventInput, Prisma.EventContactUncheckedCreateWithoutEventInput>
  connectOrCreate?: Prisma.EventContactCreateOrConnectWithoutEventInput
  connect?: Prisma.EventContactWhereUniqueInput
}

export type EventContactUncheckedCreateNestedOneWithoutEventInput = {
  create?: Prisma.XOR<Prisma.EventContactCreateWithoutEventInput, Prisma.EventContactUncheckedCreateWithoutEventInput>
  connectOrCreate?: Prisma.EventContactCreateOrConnectWithoutEventInput
  connect?: Prisma.EventContactWhereUniqueInput
}

export type EventContactUpdateOneWithoutEventNestedInput = {
  create?: Prisma.XOR<Prisma.EventContactCreateWithoutEventInput, Prisma.EventContactUncheckedCreateWithoutEventInput>
  connectOrCreate?: Prisma.EventContactCreateOrConnectWithoutEventInput
  upsert?: Prisma.EventContactUpsertWithoutEventInput
  disconnect?: Prisma.EventContactWhereInput | boolean
  delete?: Prisma.EventContactWhereInput | boolean
  connect?: Prisma.EventContactWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.EventContactUpdateToOneWithWhereWithoutEventInput, Prisma.EventContactUpdateWithoutEventInput>, Prisma.EventContactUncheckedUpdateWithoutEventInput>
}

export type EventContactUncheckedUpdateOneWithoutEventNestedInput = {
  create?: Prisma.XOR<Prisma.EventContactCreateWithoutEventInput, Prisma.EventContactUncheckedCreateWithoutEventInput>
  connectOrCreate?: Prisma.EventContactCreateOrConnectWithoutEventInput
  upsert?: Prisma.EventContactUpsertWithoutEventInput
  disconnect?: Prisma.EventContactWhereInput | boolean
  delete?: Prisma.EventContactWhereInput | boolean
  connect?: Prisma.EventContactWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.EventContactUpdateToOneWithWhereWithoutEventInput, Prisma.EventContactUpdateWithoutEventInput>, Prisma.EventContactUncheckedUpdateWithoutEventInput>
}

export type EventContactCreateWithoutEventInput = {
  name: string
  email?: string | null
  phone?: string | null
  message?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type EventContactUncheckedCreateWithoutEventInput = {
  name: string
  email?: string | null
  phone?: string | null
  message?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type EventContactCreateOrConnectWithoutEventInput = {
  where: Prisma.EventContactWhereUniqueInput
  create: Prisma.XOR<Prisma.EventContactCreateWithoutEventInput, Prisma.EventContactUncheckedCreateWithoutEventInput>
}

export type EventContactUpsertWithoutEventInput = {
  update: Prisma.XOR<Prisma.EventContactUpdateWithoutEventInput, Prisma.EventContactUncheckedUpdateWithoutEventInput>
  create: Prisma.XOR<Prisma.EventContactCreateWithoutEventInput, Prisma.EventContactUncheckedCreateWithoutEventInput>
  where?: Prisma.EventContactWhereInput
}

export type EventContactUpdateToOneWithWhereWithoutEventInput = {
  where?: Prisma.EventContactWhereInput
  data: Prisma.XOR<Prisma.EventContactUpdateWithoutEventInput, Prisma.EventContactUncheckedUpdateWithoutEventInput>
}

export type EventContactUpdateWithoutEventInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EventContactUncheckedUpdateWithoutEventInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type EventContactSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  phone?: boolean
  message?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  event?: boolean | Prisma.EventDetailsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventContact"]>

export type EventContactSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  phone?: boolean
  message?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  event?: boolean | Prisma.EventDetailsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventContact"]>

export type EventContactSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  phone?: boolean
  message?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  event?: boolean | Prisma.EventDetailsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventContact"]>

export type EventContactSelectScalar = {
  id?: boolean
  name?: boolean
  email?: boolean
  phone?: boolean
  message?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}

export type EventContactOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "email" | "phone" | "message" | "createdAt" | "updatedAt" | "deletedAt", ExtArgs["result"]["eventContact"]>
export type EventContactInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  event?: boolean | Prisma.EventDetailsDefaultArgs<ExtArgs>
}
export type EventContactIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  event?: boolean | Prisma.EventDetailsDefaultArgs<ExtArgs>
}
export type EventContactIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  event?: boolean | Prisma.EventDetailsDefaultArgs<ExtArgs>
}

export type $EventContactPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "EventContact"
  objects: {
    event: Prisma.$EventDetailsPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    email: string | null
    phone: string | null
    message: string | null
    createdAt: Date
    updatedAt: Date
    deletedAt: Date | null
  }, ExtArgs["result"]["eventContact"]>
  composites: {}
}

export type EventContactGetPayload<S extends boolean | null | undefined | EventContactDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EventContactPayload, S>

export type EventContactCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EventContactFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EventContactCountAggregateInputType | true
  }

export interface EventContactDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['EventContact'], meta: { name: 'EventContact' } }
  /**
   * Find zero or one EventContact that matches the filter.
   * @param {EventContactFindUniqueArgs} args - Arguments to find a EventContact
   * @example
   * // Get one EventContact
   * const eventContact = await prisma.eventContact.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EventContactFindUniqueArgs>(args: Prisma.SelectSubset<T, EventContactFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EventContactClient<runtime.Types.Result.GetResult<Prisma.$EventContactPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one EventContact that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EventContactFindUniqueOrThrowArgs} args - Arguments to find a EventContact
   * @example
   * // Get one EventContact
   * const eventContact = await prisma.eventContact.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EventContactFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EventContactFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EventContactClient<runtime.Types.Result.GetResult<Prisma.$EventContactPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EventContact that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventContactFindFirstArgs} args - Arguments to find a EventContact
   * @example
   * // Get one EventContact
   * const eventContact = await prisma.eventContact.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EventContactFindFirstArgs>(args?: Prisma.SelectSubset<T, EventContactFindFirstArgs<ExtArgs>>): Prisma.Prisma__EventContactClient<runtime.Types.Result.GetResult<Prisma.$EventContactPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EventContact that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventContactFindFirstOrThrowArgs} args - Arguments to find a EventContact
   * @example
   * // Get one EventContact
   * const eventContact = await prisma.eventContact.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EventContactFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EventContactFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EventContactClient<runtime.Types.Result.GetResult<Prisma.$EventContactPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more EventContacts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventContactFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all EventContacts
   * const eventContacts = await prisma.eventContact.findMany()
   * 
   * // Get first 10 EventContacts
   * const eventContacts = await prisma.eventContact.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const eventContactWithIdOnly = await prisma.eventContact.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EventContactFindManyArgs>(args?: Prisma.SelectSubset<T, EventContactFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventContactPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a EventContact.
   * @param {EventContactCreateArgs} args - Arguments to create a EventContact.
   * @example
   * // Create one EventContact
   * const EventContact = await prisma.eventContact.create({
   *   data: {
   *     // ... data to create a EventContact
   *   }
   * })
   * 
   */
  create<T extends EventContactCreateArgs>(args: Prisma.SelectSubset<T, EventContactCreateArgs<ExtArgs>>): Prisma.Prisma__EventContactClient<runtime.Types.Result.GetResult<Prisma.$EventContactPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many EventContacts.
   * @param {EventContactCreateManyArgs} args - Arguments to create many EventContacts.
   * @example
   * // Create many EventContacts
   * const eventContact = await prisma.eventContact.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EventContactCreateManyArgs>(args?: Prisma.SelectSubset<T, EventContactCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many EventContacts and returns the data saved in the database.
   * @param {EventContactCreateManyAndReturnArgs} args - Arguments to create many EventContacts.
   * @example
   * // Create many EventContacts
   * const eventContact = await prisma.eventContact.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many EventContacts and only return the `id`
   * const eventContactWithIdOnly = await prisma.eventContact.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EventContactCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EventContactCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventContactPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a EventContact.
   * @param {EventContactDeleteArgs} args - Arguments to delete one EventContact.
   * @example
   * // Delete one EventContact
   * const EventContact = await prisma.eventContact.delete({
   *   where: {
   *     // ... filter to delete one EventContact
   *   }
   * })
   * 
   */
  delete<T extends EventContactDeleteArgs>(args: Prisma.SelectSubset<T, EventContactDeleteArgs<ExtArgs>>): Prisma.Prisma__EventContactClient<runtime.Types.Result.GetResult<Prisma.$EventContactPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one EventContact.
   * @param {EventContactUpdateArgs} args - Arguments to update one EventContact.
   * @example
   * // Update one EventContact
   * const eventContact = await prisma.eventContact.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EventContactUpdateArgs>(args: Prisma.SelectSubset<T, EventContactUpdateArgs<ExtArgs>>): Prisma.Prisma__EventContactClient<runtime.Types.Result.GetResult<Prisma.$EventContactPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more EventContacts.
   * @param {EventContactDeleteManyArgs} args - Arguments to filter EventContacts to delete.
   * @example
   * // Delete a few EventContacts
   * const { count } = await prisma.eventContact.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EventContactDeleteManyArgs>(args?: Prisma.SelectSubset<T, EventContactDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EventContacts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventContactUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many EventContacts
   * const eventContact = await prisma.eventContact.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EventContactUpdateManyArgs>(args: Prisma.SelectSubset<T, EventContactUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EventContacts and returns the data updated in the database.
   * @param {EventContactUpdateManyAndReturnArgs} args - Arguments to update many EventContacts.
   * @example
   * // Update many EventContacts
   * const eventContact = await prisma.eventContact.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more EventContacts and only return the `id`
   * const eventContactWithIdOnly = await prisma.eventContact.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EventContactUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EventContactUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventContactPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one EventContact.
   * @param {EventContactUpsertArgs} args - Arguments to update or create a EventContact.
   * @example
   * // Update or create a EventContact
   * const eventContact = await prisma.eventContact.upsert({
   *   create: {
   *     // ... data to create a EventContact
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the EventContact we want to update
   *   }
   * })
   */
  upsert<T extends EventContactUpsertArgs>(args: Prisma.SelectSubset<T, EventContactUpsertArgs<ExtArgs>>): Prisma.Prisma__EventContactClient<runtime.Types.Result.GetResult<Prisma.$EventContactPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of EventContacts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventContactCountArgs} args - Arguments to filter EventContacts to count.
   * @example
   * // Count the number of EventContacts
   * const count = await prisma.eventContact.count({
   *   where: {
   *     // ... the filter for the EventContacts we want to count
   *   }
   * })
  **/
  count<T extends EventContactCountArgs>(
    args?: Prisma.Subset<T, EventContactCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EventContactCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a EventContact.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventContactAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EventContactAggregateArgs>(args: Prisma.Subset<T, EventContactAggregateArgs>): Prisma.PrismaPromise<GetEventContactAggregateType<T>>

  /**
   * Group by EventContact.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventContactGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EventContactGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EventContactGroupByArgs['orderBy'] }
      : { orderBy?: EventContactGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EventContactGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEventContactGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the EventContact model
 */
readonly fields: EventContactFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for EventContact.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EventContactClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  event<T extends Prisma.EventDetailsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EventDetailsDefaultArgs<ExtArgs>>): Prisma.Prisma__EventDetailsClient<runtime.Types.Result.GetResult<Prisma.$EventDetailsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the EventContact model
 */
export interface EventContactFieldRefs {
  readonly id: Prisma.FieldRef<"EventContact", 'String'>
  readonly name: Prisma.FieldRef<"EventContact", 'String'>
  readonly email: Prisma.FieldRef<"EventContact", 'String'>
  readonly phone: Prisma.FieldRef<"EventContact", 'String'>
  readonly message: Prisma.FieldRef<"EventContact", 'String'>
  readonly createdAt: Prisma.FieldRef<"EventContact", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"EventContact", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"EventContact", 'DateTime'>
}
    

// Custom InputTypes
/**
 * EventContact findUnique
 */
export type EventContactFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventContact
   */
  select?: Prisma.EventContactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventContact
   */
  omit?: Prisma.EventContactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventContactInclude<ExtArgs> | null
  /**
   * Filter, which EventContact to fetch.
   */
  where: Prisma.EventContactWhereUniqueInput
}

/**
 * EventContact findUniqueOrThrow
 */
export type EventContactFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventContact
   */
  select?: Prisma.EventContactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventContact
   */
  omit?: Prisma.EventContactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventContactInclude<ExtArgs> | null
  /**
   * Filter, which EventContact to fetch.
   */
  where: Prisma.EventContactWhereUniqueInput
}

/**
 * EventContact findFirst
 */
export type EventContactFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventContact
   */
  select?: Prisma.EventContactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventContact
   */
  omit?: Prisma.EventContactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventContactInclude<ExtArgs> | null
  /**
   * Filter, which EventContact to fetch.
   */
  where?: Prisma.EventContactWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventContacts to fetch.
   */
  orderBy?: Prisma.EventContactOrderByWithRelationInput | Prisma.EventContactOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EventContacts.
   */
  cursor?: Prisma.EventContactWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventContacts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventContacts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventContacts.
   */
  distinct?: Prisma.EventContactScalarFieldEnum | Prisma.EventContactScalarFieldEnum[]
}

/**
 * EventContact findFirstOrThrow
 */
export type EventContactFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventContact
   */
  select?: Prisma.EventContactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventContact
   */
  omit?: Prisma.EventContactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventContactInclude<ExtArgs> | null
  /**
   * Filter, which EventContact to fetch.
   */
  where?: Prisma.EventContactWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventContacts to fetch.
   */
  orderBy?: Prisma.EventContactOrderByWithRelationInput | Prisma.EventContactOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EventContacts.
   */
  cursor?: Prisma.EventContactWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventContacts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventContacts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventContacts.
   */
  distinct?: Prisma.EventContactScalarFieldEnum | Prisma.EventContactScalarFieldEnum[]
}

/**
 * EventContact findMany
 */
export type EventContactFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventContact
   */
  select?: Prisma.EventContactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventContact
   */
  omit?: Prisma.EventContactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventContactInclude<ExtArgs> | null
  /**
   * Filter, which EventContacts to fetch.
   */
  where?: Prisma.EventContactWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventContacts to fetch.
   */
  orderBy?: Prisma.EventContactOrderByWithRelationInput | Prisma.EventContactOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing EventContacts.
   */
  cursor?: Prisma.EventContactWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventContacts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventContacts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventContacts.
   */
  distinct?: Prisma.EventContactScalarFieldEnum | Prisma.EventContactScalarFieldEnum[]
}

/**
 * EventContact create
 */
export type EventContactCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventContact
   */
  select?: Prisma.EventContactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventContact
   */
  omit?: Prisma.EventContactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventContactInclude<ExtArgs> | null
  /**
   * The data needed to create a EventContact.
   */
  data: Prisma.XOR<Prisma.EventContactCreateInput, Prisma.EventContactUncheckedCreateInput>
}

/**
 * EventContact createMany
 */
export type EventContactCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many EventContacts.
   */
  data: Prisma.EventContactCreateManyInput | Prisma.EventContactCreateManyInput[]
}

/**
 * EventContact createManyAndReturn
 */
export type EventContactCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventContact
   */
  select?: Prisma.EventContactSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EventContact
   */
  omit?: Prisma.EventContactOmit<ExtArgs> | null
  /**
   * The data used to create many EventContacts.
   */
  data: Prisma.EventContactCreateManyInput | Prisma.EventContactCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventContactIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * EventContact update
 */
export type EventContactUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventContact
   */
  select?: Prisma.EventContactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventContact
   */
  omit?: Prisma.EventContactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventContactInclude<ExtArgs> | null
  /**
   * The data needed to update a EventContact.
   */
  data: Prisma.XOR<Prisma.EventContactUpdateInput, Prisma.EventContactUncheckedUpdateInput>
  /**
   * Choose, which EventContact to update.
   */
  where: Prisma.EventContactWhereUniqueInput
}

/**
 * EventContact updateMany
 */
export type EventContactUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update EventContacts.
   */
  data: Prisma.XOR<Prisma.EventContactUpdateManyMutationInput, Prisma.EventContactUncheckedUpdateManyInput>
  /**
   * Filter which EventContacts to update
   */
  where?: Prisma.EventContactWhereInput
  /**
   * Limit how many EventContacts to update.
   */
  limit?: number
}

/**
 * EventContact updateManyAndReturn
 */
export type EventContactUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventContact
   */
  select?: Prisma.EventContactSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EventContact
   */
  omit?: Prisma.EventContactOmit<ExtArgs> | null
  /**
   * The data used to update EventContacts.
   */
  data: Prisma.XOR<Prisma.EventContactUpdateManyMutationInput, Prisma.EventContactUncheckedUpdateManyInput>
  /**
   * Filter which EventContacts to update
   */
  where?: Prisma.EventContactWhereInput
  /**
   * Limit how many EventContacts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventContactIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * EventContact upsert
 */
export type EventContactUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventContact
   */
  select?: Prisma.EventContactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventContact
   */
  omit?: Prisma.EventContactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventContactInclude<ExtArgs> | null
  /**
   * The filter to search for the EventContact to update in case it exists.
   */
  where: Prisma.EventContactWhereUniqueInput
  /**
   * In case the EventContact found by the `where` argument doesn't exist, create a new EventContact with this data.
   */
  create: Prisma.XOR<Prisma.EventContactCreateInput, Prisma.EventContactUncheckedCreateInput>
  /**
   * In case the EventContact was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EventContactUpdateInput, Prisma.EventContactUncheckedUpdateInput>
}

/**
 * EventContact delete
 */
export type EventContactDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventContact
   */
  select?: Prisma.EventContactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventContact
   */
  omit?: Prisma.EventContactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventContactInclude<ExtArgs> | null
  /**
   * Filter which EventContact to delete.
   */
  where: Prisma.EventContactWhereUniqueInput
}

/**
 * EventContact deleteMany
 */
export type EventContactDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EventContacts to delete
   */
  where?: Prisma.EventContactWhereInput
  /**
   * Limit how many EventContacts to delete.
   */
  limit?: number
}

/**
 * EventContact without action
 */
export type EventContactDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventContact
   */
  select?: Prisma.EventContactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventContact
   */
  omit?: Prisma.EventContactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventContactInclude<ExtArgs> | null
}
