
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `EventDetails` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model EventDetails
 * 
 */
export type EventDetailsModel = runtime.Types.Result.DefaultSelection<Prisma.$EventDetailsPayload>

export type AggregateEventDetails = {
  _count: EventDetailsCountAggregateOutputType | null
  _min: EventDetailsMinAggregateOutputType | null
  _max: EventDetailsMaxAggregateOutputType | null
}

export type EventDetailsMinAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  location: string | null
  osaAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type EventDetailsMaxAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  location: string | null
  osaAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type EventDetailsCountAggregateOutputType = {
  id: number
  name: number
  description: number
  location: number
  osaAt: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  _all: number
}


export type EventDetailsMinAggregateInputType = {
  id?: true
  name?: true
  description?: true
  location?: true
  osaAt?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type EventDetailsMaxAggregateInputType = {
  id?: true
  name?: true
  description?: true
  location?: true
  osaAt?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type EventDetailsCountAggregateInputType = {
  id?: true
  name?: true
  description?: true
  location?: true
  osaAt?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  _all?: true
}

export type EventDetailsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EventDetails to aggregate.
   */
  where?: Prisma.EventDetailsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventDetails to fetch.
   */
  orderBy?: Prisma.EventDetailsOrderByWithRelationInput | Prisma.EventDetailsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EventDetailsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventDetails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventDetails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned EventDetails
  **/
  _count?: true | EventDetailsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EventDetailsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EventDetailsMaxAggregateInputType
}

export type GetEventDetailsAggregateType<T extends EventDetailsAggregateArgs> = {
      [P in keyof T & keyof AggregateEventDetails]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEventDetails[P]>
    : Prisma.GetScalarType<T[P], AggregateEventDetails[P]>
}




export type EventDetailsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EventDetailsWhereInput
  orderBy?: Prisma.EventDetailsOrderByWithAggregationInput | Prisma.EventDetailsOrderByWithAggregationInput[]
  by: Prisma.EventDetailsScalarFieldEnum[] | Prisma.EventDetailsScalarFieldEnum
  having?: Prisma.EventDetailsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EventDetailsCountAggregateInputType | true
  _min?: EventDetailsMinAggregateInputType
  _max?: EventDetailsMaxAggregateInputType
}

export type EventDetailsGroupByOutputType = {
  id: string
  name: string
  description: string | null
  location: string | null
  osaAt: Date | null
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  _count: EventDetailsCountAggregateOutputType | null
  _min: EventDetailsMinAggregateOutputType | null
  _max: EventDetailsMaxAggregateOutputType | null
}

export type GetEventDetailsGroupByPayload<T extends EventDetailsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EventDetailsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EventDetailsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EventDetailsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EventDetailsGroupByOutputType[P]>
      }
    >
  >



export type EventDetailsWhereInput = {
  AND?: Prisma.EventDetailsWhereInput | Prisma.EventDetailsWhereInput[]
  OR?: Prisma.EventDetailsWhereInput[]
  NOT?: Prisma.EventDetailsWhereInput | Prisma.EventDetailsWhereInput[]
  id?: Prisma.StringFilter<"EventDetails"> | string
  name?: Prisma.StringFilter<"EventDetails"> | string
  description?: Prisma.StringNullableFilter<"EventDetails"> | string | null
  location?: Prisma.StringNullableFilter<"EventDetails"> | string | null
  osaAt?: Prisma.DateTimeNullableFilter<"EventDetails"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"EventDetails"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EventDetails"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"EventDetails"> | Date | string | null
  event?: Prisma.XOR<Prisma.EventScalarRelationFilter, Prisma.EventWhereInput>
  contact?: Prisma.XOR<Prisma.EventContactNullableScalarRelationFilter, Prisma.EventContactWhereInput> | null
}

export type EventDetailsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  location?: Prisma.SortOrderInput | Prisma.SortOrder
  osaAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  event?: Prisma.EventOrderByWithRelationInput
  contact?: Prisma.EventContactOrderByWithRelationInput
}

export type EventDetailsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.EventDetailsWhereInput | Prisma.EventDetailsWhereInput[]
  OR?: Prisma.EventDetailsWhereInput[]
  NOT?: Prisma.EventDetailsWhereInput | Prisma.EventDetailsWhereInput[]
  name?: Prisma.StringFilter<"EventDetails"> | string
  description?: Prisma.StringNullableFilter<"EventDetails"> | string | null
  location?: Prisma.StringNullableFilter<"EventDetails"> | string | null
  osaAt?: Prisma.DateTimeNullableFilter<"EventDetails"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"EventDetails"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EventDetails"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"EventDetails"> | Date | string | null
  event?: Prisma.XOR<Prisma.EventScalarRelationFilter, Prisma.EventWhereInput>
  contact?: Prisma.XOR<Prisma.EventContactNullableScalarRelationFilter, Prisma.EventContactWhereInput> | null
}, "id" | "id">

export type EventDetailsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  location?: Prisma.SortOrderInput | Prisma.SortOrder
  osaAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.EventDetailsCountOrderByAggregateInput
  _max?: Prisma.EventDetailsMaxOrderByAggregateInput
  _min?: Prisma.EventDetailsMinOrderByAggregateInput
}

export type EventDetailsScalarWhereWithAggregatesInput = {
  AND?: Prisma.EventDetailsScalarWhereWithAggregatesInput | Prisma.EventDetailsScalarWhereWithAggregatesInput[]
  OR?: Prisma.EventDetailsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EventDetailsScalarWhereWithAggregatesInput | Prisma.EventDetailsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"EventDetails"> | string
  name?: Prisma.StringWithAggregatesFilter<"EventDetails"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"EventDetails"> | string | null
  location?: Prisma.StringNullableWithAggregatesFilter<"EventDetails"> | string | null
  osaAt?: Prisma.DateTimeNullableWithAggregatesFilter<"EventDetails"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"EventDetails"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"EventDetails"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"EventDetails"> | Date | string | null
}

export type EventDetailsCreateInput = {
  name: string
  description?: string | null
  location?: string | null
  osaAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  event: Prisma.EventCreateNestedOneWithoutDetailsInput
  contact?: Prisma.EventContactCreateNestedOneWithoutEventInput
}

export type EventDetailsUncheckedCreateInput = {
  id: string
  name: string
  description?: string | null
  location?: string | null
  osaAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  contact?: Prisma.EventContactUncheckedCreateNestedOneWithoutEventInput
}

export type EventDetailsUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  osaAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  event?: Prisma.EventUpdateOneRequiredWithoutDetailsNestedInput
  contact?: Prisma.EventContactUpdateOneWithoutEventNestedInput
}

export type EventDetailsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  osaAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  contact?: Prisma.EventContactUncheckedUpdateOneWithoutEventNestedInput
}

export type EventDetailsCreateManyInput = {
  id: string
  name: string
  description?: string | null
  location?: string | null
  osaAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type EventDetailsUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  osaAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EventDetailsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  osaAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EventDetailsNullableScalarRelationFilter = {
  is?: Prisma.EventDetailsWhereInput | null
  isNot?: Prisma.EventDetailsWhereInput | null
}

export type EventDetailsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  location?: Prisma.SortOrder
  osaAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type EventDetailsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  location?: Prisma.SortOrder
  osaAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type EventDetailsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  location?: Prisma.SortOrder
  osaAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type EventDetailsScalarRelationFilter = {
  is?: Prisma.EventDetailsWhereInput
  isNot?: Prisma.EventDetailsWhereInput
}

export type EventDetailsCreateNestedOneWithoutEventInput = {
  create?: Prisma.XOR<Prisma.EventDetailsCreateWithoutEventInput, Prisma.EventDetailsUncheckedCreateWithoutEventInput>
  connectOrCreate?: Prisma.EventDetailsCreateOrConnectWithoutEventInput
  connect?: Prisma.EventDetailsWhereUniqueInput
}

export type EventDetailsUncheckedCreateNestedOneWithoutEventInput = {
  create?: Prisma.XOR<Prisma.EventDetailsCreateWithoutEventInput, Prisma.EventDetailsUncheckedCreateWithoutEventInput>
  connectOrCreate?: Prisma.EventDetailsCreateOrConnectWithoutEventInput
  connect?: Prisma.EventDetailsWhereUniqueInput
}

export type EventDetailsUpdateOneWithoutEventNestedInput = {
  create?: Prisma.XOR<Prisma.EventDetailsCreateWithoutEventInput, Prisma.EventDetailsUncheckedCreateWithoutEventInput>
  connectOrCreate?: Prisma.EventDetailsCreateOrConnectWithoutEventInput
  upsert?: Prisma.EventDetailsUpsertWithoutEventInput
  disconnect?: Prisma.EventDetailsWhereInput | boolean
  delete?: Prisma.EventDetailsWhereInput | boolean
  connect?: Prisma.EventDetailsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.EventDetailsUpdateToOneWithWhereWithoutEventInput, Prisma.EventDetailsUpdateWithoutEventInput>, Prisma.EventDetailsUncheckedUpdateWithoutEventInput>
}

export type EventDetailsUncheckedUpdateOneWithoutEventNestedInput = {
  create?: Prisma.XOR<Prisma.EventDetailsCreateWithoutEventInput, Prisma.EventDetailsUncheckedCreateWithoutEventInput>
  connectOrCreate?: Prisma.EventDetailsCreateOrConnectWithoutEventInput
  upsert?: Prisma.EventDetailsUpsertWithoutEventInput
  disconnect?: Prisma.EventDetailsWhereInput | boolean
  delete?: Prisma.EventDetailsWhereInput | boolean
  connect?: Prisma.EventDetailsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.EventDetailsUpdateToOneWithWhereWithoutEventInput, Prisma.EventDetailsUpdateWithoutEventInput>, Prisma.EventDetailsUncheckedUpdateWithoutEventInput>
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type EventDetailsCreateNestedOneWithoutContactInput = {
  create?: Prisma.XOR<Prisma.EventDetailsCreateWithoutContactInput, Prisma.EventDetailsUncheckedCreateWithoutContactInput>
  connectOrCreate?: Prisma.EventDetailsCreateOrConnectWithoutContactInput
  connect?: Prisma.EventDetailsWhereUniqueInput
}

export type EventDetailsUpdateOneRequiredWithoutContactNestedInput = {
  create?: Prisma.XOR<Prisma.EventDetailsCreateWithoutContactInput, Prisma.EventDetailsUncheckedCreateWithoutContactInput>
  connectOrCreate?: Prisma.EventDetailsCreateOrConnectWithoutContactInput
  upsert?: Prisma.EventDetailsUpsertWithoutContactInput
  connect?: Prisma.EventDetailsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.EventDetailsUpdateToOneWithWhereWithoutContactInput, Prisma.EventDetailsUpdateWithoutContactInput>, Prisma.EventDetailsUncheckedUpdateWithoutContactInput>
}

export type EventDetailsCreateWithoutEventInput = {
  name: string
  description?: string | null
  location?: string | null
  osaAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  contact?: Prisma.EventContactCreateNestedOneWithoutEventInput
}

export type EventDetailsUncheckedCreateWithoutEventInput = {
  name: string
  description?: string | null
  location?: string | null
  osaAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  contact?: Prisma.EventContactUncheckedCreateNestedOneWithoutEventInput
}

export type EventDetailsCreateOrConnectWithoutEventInput = {
  where: Prisma.EventDetailsWhereUniqueInput
  create: Prisma.XOR<Prisma.EventDetailsCreateWithoutEventInput, Prisma.EventDetailsUncheckedCreateWithoutEventInput>
}

export type EventDetailsUpsertWithoutEventInput = {
  update: Prisma.XOR<Prisma.EventDetailsUpdateWithoutEventInput, Prisma.EventDetailsUncheckedUpdateWithoutEventInput>
  create: Prisma.XOR<Prisma.EventDetailsCreateWithoutEventInput, Prisma.EventDetailsUncheckedCreateWithoutEventInput>
  where?: Prisma.EventDetailsWhereInput
}

export type EventDetailsUpdateToOneWithWhereWithoutEventInput = {
  where?: Prisma.EventDetailsWhereInput
  data: Prisma.XOR<Prisma.EventDetailsUpdateWithoutEventInput, Prisma.EventDetailsUncheckedUpdateWithoutEventInput>
}

export type EventDetailsUpdateWithoutEventInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  osaAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  contact?: Prisma.EventContactUpdateOneWithoutEventNestedInput
}

export type EventDetailsUncheckedUpdateWithoutEventInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  osaAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  contact?: Prisma.EventContactUncheckedUpdateOneWithoutEventNestedInput
}

export type EventDetailsCreateWithoutContactInput = {
  name: string
  description?: string | null
  location?: string | null
  osaAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  event: Prisma.EventCreateNestedOneWithoutDetailsInput
}

export type EventDetailsUncheckedCreateWithoutContactInput = {
  id: string
  name: string
  description?: string | null
  location?: string | null
  osaAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type EventDetailsCreateOrConnectWithoutContactInput = {
  where: Prisma.EventDetailsWhereUniqueInput
  create: Prisma.XOR<Prisma.EventDetailsCreateWithoutContactInput, Prisma.EventDetailsUncheckedCreateWithoutContactInput>
}

export type EventDetailsUpsertWithoutContactInput = {
  update: Prisma.XOR<Prisma.EventDetailsUpdateWithoutContactInput, Prisma.EventDetailsUncheckedUpdateWithoutContactInput>
  create: Prisma.XOR<Prisma.EventDetailsCreateWithoutContactInput, Prisma.EventDetailsUncheckedCreateWithoutContactInput>
  where?: Prisma.EventDetailsWhereInput
}

export type EventDetailsUpdateToOneWithWhereWithoutContactInput = {
  where?: Prisma.EventDetailsWhereInput
  data: Prisma.XOR<Prisma.EventDetailsUpdateWithoutContactInput, Prisma.EventDetailsUncheckedUpdateWithoutContactInput>
}

export type EventDetailsUpdateWithoutContactInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  osaAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  event?: Prisma.EventUpdateOneRequiredWithoutDetailsNestedInput
}

export type EventDetailsUncheckedUpdateWithoutContactInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  osaAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type EventDetailsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  location?: boolean
  osaAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  contact?: boolean | Prisma.EventDetails$contactArgs<ExtArgs>
}, ExtArgs["result"]["eventDetails"]>

export type EventDetailsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  location?: boolean
  osaAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventDetails"]>

export type EventDetailsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  location?: boolean
  osaAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventDetails"]>

export type EventDetailsSelectScalar = {
  id?: boolean
  name?: boolean
  description?: boolean
  location?: boolean
  osaAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}

export type EventDetailsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "description" | "location" | "osaAt" | "createdAt" | "updatedAt" | "deletedAt", ExtArgs["result"]["eventDetails"]>
export type EventDetailsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  contact?: boolean | Prisma.EventDetails$contactArgs<ExtArgs>
}
export type EventDetailsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}
export type EventDetailsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}

export type $EventDetailsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "EventDetails"
  objects: {
    event: Prisma.$EventPayload<ExtArgs>
    contact: Prisma.$EventContactPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    description: string | null
    location: string | null
    osaAt: Date | null
    createdAt: Date
    updatedAt: Date
    deletedAt: Date | null
  }, ExtArgs["result"]["eventDetails"]>
  composites: {}
}

export type EventDetailsGetPayload<S extends boolean | null | undefined | EventDetailsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EventDetailsPayload, S>

export type EventDetailsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EventDetailsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EventDetailsCountAggregateInputType | true
  }

export interface EventDetailsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['EventDetails'], meta: { name: 'EventDetails' } }
  /**
   * Find zero or one EventDetails that matches the filter.
   * @param {EventDetailsFindUniqueArgs} args - Arguments to find a EventDetails
   * @example
   * // Get one EventDetails
   * const eventDetails = await prisma.eventDetails.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EventDetailsFindUniqueArgs>(args: Prisma.SelectSubset<T, EventDetailsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EventDetailsClient<runtime.Types.Result.GetResult<Prisma.$EventDetailsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one EventDetails that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EventDetailsFindUniqueOrThrowArgs} args - Arguments to find a EventDetails
   * @example
   * // Get one EventDetails
   * const eventDetails = await prisma.eventDetails.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EventDetailsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EventDetailsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EventDetailsClient<runtime.Types.Result.GetResult<Prisma.$EventDetailsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EventDetails that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventDetailsFindFirstArgs} args - Arguments to find a EventDetails
   * @example
   * // Get one EventDetails
   * const eventDetails = await prisma.eventDetails.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EventDetailsFindFirstArgs>(args?: Prisma.SelectSubset<T, EventDetailsFindFirstArgs<ExtArgs>>): Prisma.Prisma__EventDetailsClient<runtime.Types.Result.GetResult<Prisma.$EventDetailsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EventDetails that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventDetailsFindFirstOrThrowArgs} args - Arguments to find a EventDetails
   * @example
   * // Get one EventDetails
   * const eventDetails = await prisma.eventDetails.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EventDetailsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EventDetailsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EventDetailsClient<runtime.Types.Result.GetResult<Prisma.$EventDetailsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more EventDetails that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventDetailsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all EventDetails
   * const eventDetails = await prisma.eventDetails.findMany()
   * 
   * // Get first 10 EventDetails
   * const eventDetails = await prisma.eventDetails.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const eventDetailsWithIdOnly = await prisma.eventDetails.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EventDetailsFindManyArgs>(args?: Prisma.SelectSubset<T, EventDetailsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventDetailsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a EventDetails.
   * @param {EventDetailsCreateArgs} args - Arguments to create a EventDetails.
   * @example
   * // Create one EventDetails
   * const EventDetails = await prisma.eventDetails.create({
   *   data: {
   *     // ... data to create a EventDetails
   *   }
   * })
   * 
   */
  create<T extends EventDetailsCreateArgs>(args: Prisma.SelectSubset<T, EventDetailsCreateArgs<ExtArgs>>): Prisma.Prisma__EventDetailsClient<runtime.Types.Result.GetResult<Prisma.$EventDetailsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many EventDetails.
   * @param {EventDetailsCreateManyArgs} args - Arguments to create many EventDetails.
   * @example
   * // Create many EventDetails
   * const eventDetails = await prisma.eventDetails.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EventDetailsCreateManyArgs>(args?: Prisma.SelectSubset<T, EventDetailsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many EventDetails and returns the data saved in the database.
   * @param {EventDetailsCreateManyAndReturnArgs} args - Arguments to create many EventDetails.
   * @example
   * // Create many EventDetails
   * const eventDetails = await prisma.eventDetails.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many EventDetails and only return the `id`
   * const eventDetailsWithIdOnly = await prisma.eventDetails.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EventDetailsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EventDetailsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventDetailsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a EventDetails.
   * @param {EventDetailsDeleteArgs} args - Arguments to delete one EventDetails.
   * @example
   * // Delete one EventDetails
   * const EventDetails = await prisma.eventDetails.delete({
   *   where: {
   *     // ... filter to delete one EventDetails
   *   }
   * })
   * 
   */
  delete<T extends EventDetailsDeleteArgs>(args: Prisma.SelectSubset<T, EventDetailsDeleteArgs<ExtArgs>>): Prisma.Prisma__EventDetailsClient<runtime.Types.Result.GetResult<Prisma.$EventDetailsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one EventDetails.
   * @param {EventDetailsUpdateArgs} args - Arguments to update one EventDetails.
   * @example
   * // Update one EventDetails
   * const eventDetails = await prisma.eventDetails.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EventDetailsUpdateArgs>(args: Prisma.SelectSubset<T, EventDetailsUpdateArgs<ExtArgs>>): Prisma.Prisma__EventDetailsClient<runtime.Types.Result.GetResult<Prisma.$EventDetailsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more EventDetails.
   * @param {EventDetailsDeleteManyArgs} args - Arguments to filter EventDetails to delete.
   * @example
   * // Delete a few EventDetails
   * const { count } = await prisma.eventDetails.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EventDetailsDeleteManyArgs>(args?: Prisma.SelectSubset<T, EventDetailsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EventDetails.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventDetailsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many EventDetails
   * const eventDetails = await prisma.eventDetails.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EventDetailsUpdateManyArgs>(args: Prisma.SelectSubset<T, EventDetailsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EventDetails and returns the data updated in the database.
   * @param {EventDetailsUpdateManyAndReturnArgs} args - Arguments to update many EventDetails.
   * @example
   * // Update many EventDetails
   * const eventDetails = await prisma.eventDetails.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more EventDetails and only return the `id`
   * const eventDetailsWithIdOnly = await prisma.eventDetails.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EventDetailsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EventDetailsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventDetailsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one EventDetails.
   * @param {EventDetailsUpsertArgs} args - Arguments to update or create a EventDetails.
   * @example
   * // Update or create a EventDetails
   * const eventDetails = await prisma.eventDetails.upsert({
   *   create: {
   *     // ... data to create a EventDetails
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the EventDetails we want to update
   *   }
   * })
   */
  upsert<T extends EventDetailsUpsertArgs>(args: Prisma.SelectSubset<T, EventDetailsUpsertArgs<ExtArgs>>): Prisma.Prisma__EventDetailsClient<runtime.Types.Result.GetResult<Prisma.$EventDetailsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of EventDetails.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventDetailsCountArgs} args - Arguments to filter EventDetails to count.
   * @example
   * // Count the number of EventDetails
   * const count = await prisma.eventDetails.count({
   *   where: {
   *     // ... the filter for the EventDetails we want to count
   *   }
   * })
  **/
  count<T extends EventDetailsCountArgs>(
    args?: Prisma.Subset<T, EventDetailsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EventDetailsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a EventDetails.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventDetailsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EventDetailsAggregateArgs>(args: Prisma.Subset<T, EventDetailsAggregateArgs>): Prisma.PrismaPromise<GetEventDetailsAggregateType<T>>

  /**
   * Group by EventDetails.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventDetailsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EventDetailsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EventDetailsGroupByArgs['orderBy'] }
      : { orderBy?: EventDetailsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EventDetailsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEventDetailsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the EventDetails model
 */
readonly fields: EventDetailsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for EventDetails.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EventDetailsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  event<T extends Prisma.EventDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EventDefaultArgs<ExtArgs>>): Prisma.Prisma__EventClient<runtime.Types.Result.GetResult<Prisma.$EventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  contact<T extends Prisma.EventDetails$contactArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EventDetails$contactArgs<ExtArgs>>): Prisma.Prisma__EventContactClient<runtime.Types.Result.GetResult<Prisma.$EventContactPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the EventDetails model
 */
export interface EventDetailsFieldRefs {
  readonly id: Prisma.FieldRef<"EventDetails", 'String'>
  readonly name: Prisma.FieldRef<"EventDetails", 'String'>
  readonly description: Prisma.FieldRef<"EventDetails", 'String'>
  readonly location: Prisma.FieldRef<"EventDetails", 'String'>
  readonly osaAt: Prisma.FieldRef<"EventDetails", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"EventDetails", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"EventDetails", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"EventDetails", 'DateTime'>
}
    

// Custom InputTypes
/**
 * EventDetails findUnique
 */
export type EventDetailsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventDetails
   */
  select?: Prisma.EventDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventDetails
   */
  omit?: Prisma.EventDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventDetailsInclude<ExtArgs> | null
  /**
   * Filter, which EventDetails to fetch.
   */
  where: Prisma.EventDetailsWhereUniqueInput
}

/**
 * EventDetails findUniqueOrThrow
 */
export type EventDetailsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventDetails
   */
  select?: Prisma.EventDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventDetails
   */
  omit?: Prisma.EventDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventDetailsInclude<ExtArgs> | null
  /**
   * Filter, which EventDetails to fetch.
   */
  where: Prisma.EventDetailsWhereUniqueInput
}

/**
 * EventDetails findFirst
 */
export type EventDetailsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventDetails
   */
  select?: Prisma.EventDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventDetails
   */
  omit?: Prisma.EventDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventDetailsInclude<ExtArgs> | null
  /**
   * Filter, which EventDetails to fetch.
   */
  where?: Prisma.EventDetailsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventDetails to fetch.
   */
  orderBy?: Prisma.EventDetailsOrderByWithRelationInput | Prisma.EventDetailsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EventDetails.
   */
  cursor?: Prisma.EventDetailsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventDetails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventDetails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventDetails.
   */
  distinct?: Prisma.EventDetailsScalarFieldEnum | Prisma.EventDetailsScalarFieldEnum[]
}

/**
 * EventDetails findFirstOrThrow
 */
export type EventDetailsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventDetails
   */
  select?: Prisma.EventDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventDetails
   */
  omit?: Prisma.EventDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventDetailsInclude<ExtArgs> | null
  /**
   * Filter, which EventDetails to fetch.
   */
  where?: Prisma.EventDetailsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventDetails to fetch.
   */
  orderBy?: Prisma.EventDetailsOrderByWithRelationInput | Prisma.EventDetailsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EventDetails.
   */
  cursor?: Prisma.EventDetailsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventDetails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventDetails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventDetails.
   */
  distinct?: Prisma.EventDetailsScalarFieldEnum | Prisma.EventDetailsScalarFieldEnum[]
}

/**
 * EventDetails findMany
 */
export type EventDetailsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventDetails
   */
  select?: Prisma.EventDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventDetails
   */
  omit?: Prisma.EventDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventDetailsInclude<ExtArgs> | null
  /**
   * Filter, which EventDetails to fetch.
   */
  where?: Prisma.EventDetailsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventDetails to fetch.
   */
  orderBy?: Prisma.EventDetailsOrderByWithRelationInput | Prisma.EventDetailsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing EventDetails.
   */
  cursor?: Prisma.EventDetailsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventDetails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventDetails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventDetails.
   */
  distinct?: Prisma.EventDetailsScalarFieldEnum | Prisma.EventDetailsScalarFieldEnum[]
}

/**
 * EventDetails create
 */
export type EventDetailsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventDetails
   */
  select?: Prisma.EventDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventDetails
   */
  omit?: Prisma.EventDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventDetailsInclude<ExtArgs> | null
  /**
   * The data needed to create a EventDetails.
   */
  data: Prisma.XOR<Prisma.EventDetailsCreateInput, Prisma.EventDetailsUncheckedCreateInput>
}

/**
 * EventDetails createMany
 */
export type EventDetailsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many EventDetails.
   */
  data: Prisma.EventDetailsCreateManyInput | Prisma.EventDetailsCreateManyInput[]
}

/**
 * EventDetails createManyAndReturn
 */
export type EventDetailsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventDetails
   */
  select?: Prisma.EventDetailsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EventDetails
   */
  omit?: Prisma.EventDetailsOmit<ExtArgs> | null
  /**
   * The data used to create many EventDetails.
   */
  data: Prisma.EventDetailsCreateManyInput | Prisma.EventDetailsCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventDetailsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * EventDetails update
 */
export type EventDetailsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventDetails
   */
  select?: Prisma.EventDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventDetails
   */
  omit?: Prisma.EventDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventDetailsInclude<ExtArgs> | null
  /**
   * The data needed to update a EventDetails.
   */
  data: Prisma.XOR<Prisma.EventDetailsUpdateInput, Prisma.EventDetailsUncheckedUpdateInput>
  /**
   * Choose, which EventDetails to update.
   */
  where: Prisma.EventDetailsWhereUniqueInput
}

/**
 * EventDetails updateMany
 */
export type EventDetailsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update EventDetails.
   */
  data: Prisma.XOR<Prisma.EventDetailsUpdateManyMutationInput, Prisma.EventDetailsUncheckedUpdateManyInput>
  /**
   * Filter which EventDetails to update
   */
  where?: Prisma.EventDetailsWhereInput
  /**
   * Limit how many EventDetails to update.
   */
  limit?: number
}

/**
 * EventDetails updateManyAndReturn
 */
export type EventDetailsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventDetails
   */
  select?: Prisma.EventDetailsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EventDetails
   */
  omit?: Prisma.EventDetailsOmit<ExtArgs> | null
  /**
   * The data used to update EventDetails.
   */
  data: Prisma.XOR<Prisma.EventDetailsUpdateManyMutationInput, Prisma.EventDetailsUncheckedUpdateManyInput>
  /**
   * Filter which EventDetails to update
   */
  where?: Prisma.EventDetailsWhereInput
  /**
   * Limit how many EventDetails to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventDetailsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * EventDetails upsert
 */
export type EventDetailsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventDetails
   */
  select?: Prisma.EventDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventDetails
   */
  omit?: Prisma.EventDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventDetailsInclude<ExtArgs> | null
  /**
   * The filter to search for the EventDetails to update in case it exists.
   */
  where: Prisma.EventDetailsWhereUniqueInput
  /**
   * In case the EventDetails found by the `where` argument doesn't exist, create a new EventDetails with this data.
   */
  create: Prisma.XOR<Prisma.EventDetailsCreateInput, Prisma.EventDetailsUncheckedCreateInput>
  /**
   * In case the EventDetails was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EventDetailsUpdateInput, Prisma.EventDetailsUncheckedUpdateInput>
}

/**
 * EventDetails delete
 */
export type EventDetailsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventDetails
   */
  select?: Prisma.EventDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventDetails
   */
  omit?: Prisma.EventDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventDetailsInclude<ExtArgs> | null
  /**
   * Filter which EventDetails to delete.
   */
  where: Prisma.EventDetailsWhereUniqueInput
}

/**
 * EventDetails deleteMany
 */
export type EventDetailsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EventDetails to delete
   */
  where?: Prisma.EventDetailsWhereInput
  /**
   * Limit how many EventDetails to delete.
   */
  limit?: number
}

/**
 * EventDetails.contact
 */
export type EventDetails$contactArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventContact
   */
  select?: Prisma.EventContactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventContact
   */
  omit?: Prisma.EventContactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventContactInclude<ExtArgs> | null
  where?: Prisma.EventContactWhereInput
}

/**
 * EventDetails without action
 */
export type EventDetailsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventDetails
   */
  select?: Prisma.EventDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventDetails
   */
  omit?: Prisma.EventDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventDetailsInclude<ExtArgs> | null
}
