
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Guests` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Guests
 * 
 */
export type GuestsModel = runtime.Types.Result.DefaultSelection<Prisma.$GuestsPayload>

export type AggregateGuests = {
  _count: GuestsCountAggregateOutputType | null
  _avg: GuestsAvgAggregateOutputType | null
  _sum: GuestsSumAggregateOutputType | null
  _min: GuestsMinAggregateOutputType | null
  _max: GuestsMaxAggregateOutputType | null
}

export type GuestsAvgAggregateOutputType = {
  adults: number | null
  children: number | null
}

export type GuestsSumAggregateOutputType = {
  adults: number | null
  children: number | null
}

export type GuestsMinAggregateOutputType = {
  email: string | null
  name: string | null
  attending: boolean | null
  adults: number | null
  children: number | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
  reservationId: string | null
}

export type GuestsMaxAggregateOutputType = {
  email: string | null
  name: string | null
  attending: boolean | null
  adults: number | null
  children: number | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
  reservationId: string | null
}

export type GuestsCountAggregateOutputType = {
  email: number
  name: number
  attending: number
  adults: number
  children: number
  notes: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  reservationId: number
  _all: number
}


export type GuestsAvgAggregateInputType = {
  adults?: true
  children?: true
}

export type GuestsSumAggregateInputType = {
  adults?: true
  children?: true
}

export type GuestsMinAggregateInputType = {
  email?: true
  name?: true
  attending?: true
  adults?: true
  children?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  reservationId?: true
}

export type GuestsMaxAggregateInputType = {
  email?: true
  name?: true
  attending?: true
  adults?: true
  children?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  reservationId?: true
}

export type GuestsCountAggregateInputType = {
  email?: true
  name?: true
  attending?: true
  adults?: true
  children?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  reservationId?: true
  _all?: true
}

export type GuestsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Guests to aggregate.
   */
  where?: Prisma.GuestsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Guests to fetch.
   */
  orderBy?: Prisma.GuestsOrderByWithRelationInput | Prisma.GuestsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GuestsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Guests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Guests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Guests
  **/
  _count?: true | GuestsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: GuestsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: GuestsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GuestsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GuestsMaxAggregateInputType
}

export type GetGuestsAggregateType<T extends GuestsAggregateArgs> = {
      [P in keyof T & keyof AggregateGuests]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGuests[P]>
    : Prisma.GetScalarType<T[P], AggregateGuests[P]>
}




export type GuestsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GuestsWhereInput
  orderBy?: Prisma.GuestsOrderByWithAggregationInput | Prisma.GuestsOrderByWithAggregationInput[]
  by: Prisma.GuestsScalarFieldEnum[] | Prisma.GuestsScalarFieldEnum
  having?: Prisma.GuestsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GuestsCountAggregateInputType | true
  _avg?: GuestsAvgAggregateInputType
  _sum?: GuestsSumAggregateInputType
  _min?: GuestsMinAggregateInputType
  _max?: GuestsMaxAggregateInputType
}

export type GuestsGroupByOutputType = {
  email: string
  name: string
  attending: boolean
  adults: number
  children: number
  notes: string | null
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  reservationId: string
  _count: GuestsCountAggregateOutputType | null
  _avg: GuestsAvgAggregateOutputType | null
  _sum: GuestsSumAggregateOutputType | null
  _min: GuestsMinAggregateOutputType | null
  _max: GuestsMaxAggregateOutputType | null
}

export type GetGuestsGroupByPayload<T extends GuestsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GuestsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GuestsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GuestsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GuestsGroupByOutputType[P]>
      }
    >
  >



export type GuestsWhereInput = {
  AND?: Prisma.GuestsWhereInput | Prisma.GuestsWhereInput[]
  OR?: Prisma.GuestsWhereInput[]
  NOT?: Prisma.GuestsWhereInput | Prisma.GuestsWhereInput[]
  email?: Prisma.StringFilter<"Guests"> | string
  name?: Prisma.StringFilter<"Guests"> | string
  attending?: Prisma.BoolFilter<"Guests"> | boolean
  adults?: Prisma.IntFilter<"Guests"> | number
  children?: Prisma.IntFilter<"Guests"> | number
  notes?: Prisma.StringNullableFilter<"Guests"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Guests"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Guests"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Guests"> | Date | string | null
  reservationId?: Prisma.StringFilter<"Guests"> | string
  reservation?: Prisma.XOR<Prisma.EventSlotScalarRelationFilter, Prisma.EventSlotWhereInput>
}

export type GuestsOrderByWithRelationInput = {
  email?: Prisma.SortOrder
  name?: Prisma.SortOrder
  attending?: Prisma.SortOrder
  adults?: Prisma.SortOrder
  children?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  reservationId?: Prisma.SortOrder
  reservation?: Prisma.EventSlotOrderByWithRelationInput
}

export type GuestsWhereUniqueInput = Prisma.AtLeast<{
  email_reservationId?: Prisma.GuestsEmailReservationIdCompoundUniqueInput
  AND?: Prisma.GuestsWhereInput | Prisma.GuestsWhereInput[]
  OR?: Prisma.GuestsWhereInput[]
  NOT?: Prisma.GuestsWhereInput | Prisma.GuestsWhereInput[]
  email?: Prisma.StringFilter<"Guests"> | string
  name?: Prisma.StringFilter<"Guests"> | string
  attending?: Prisma.BoolFilter<"Guests"> | boolean
  adults?: Prisma.IntFilter<"Guests"> | number
  children?: Prisma.IntFilter<"Guests"> | number
  notes?: Prisma.StringNullableFilter<"Guests"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Guests"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Guests"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Guests"> | Date | string | null
  reservationId?: Prisma.StringFilter<"Guests"> | string
  reservation?: Prisma.XOR<Prisma.EventSlotScalarRelationFilter, Prisma.EventSlotWhereInput>
}, "email_reservationId">

export type GuestsOrderByWithAggregationInput = {
  email?: Prisma.SortOrder
  name?: Prisma.SortOrder
  attending?: Prisma.SortOrder
  adults?: Prisma.SortOrder
  children?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  reservationId?: Prisma.SortOrder
  _count?: Prisma.GuestsCountOrderByAggregateInput
  _avg?: Prisma.GuestsAvgOrderByAggregateInput
  _max?: Prisma.GuestsMaxOrderByAggregateInput
  _min?: Prisma.GuestsMinOrderByAggregateInput
  _sum?: Prisma.GuestsSumOrderByAggregateInput
}

export type GuestsScalarWhereWithAggregatesInput = {
  AND?: Prisma.GuestsScalarWhereWithAggregatesInput | Prisma.GuestsScalarWhereWithAggregatesInput[]
  OR?: Prisma.GuestsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GuestsScalarWhereWithAggregatesInput | Prisma.GuestsScalarWhereWithAggregatesInput[]
  email?: Prisma.StringWithAggregatesFilter<"Guests"> | string
  name?: Prisma.StringWithAggregatesFilter<"Guests"> | string
  attending?: Prisma.BoolWithAggregatesFilter<"Guests"> | boolean
  adults?: Prisma.IntWithAggregatesFilter<"Guests"> | number
  children?: Prisma.IntWithAggregatesFilter<"Guests"> | number
  notes?: Prisma.StringNullableWithAggregatesFilter<"Guests"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Guests"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Guests"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Guests"> | Date | string | null
  reservationId?: Prisma.StringWithAggregatesFilter<"Guests"> | string
}

export type GuestsCreateInput = {
  email: string
  name: string
  attending: boolean
  adults: number
  children: number
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  reservation: Prisma.EventSlotCreateNestedOneWithoutGuestsInput
}

export type GuestsUncheckedCreateInput = {
  email: string
  name: string
  attending: boolean
  adults: number
  children: number
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  reservationId: string
}

export type GuestsUpdateInput = {
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  attending?: Prisma.BoolFieldUpdateOperationsInput | boolean
  adults?: Prisma.IntFieldUpdateOperationsInput | number
  children?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reservation?: Prisma.EventSlotUpdateOneRequiredWithoutGuestsNestedInput
}

export type GuestsUncheckedUpdateInput = {
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  attending?: Prisma.BoolFieldUpdateOperationsInput | boolean
  adults?: Prisma.IntFieldUpdateOperationsInput | number
  children?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reservationId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type GuestsCreateManyInput = {
  email: string
  name: string
  attending: boolean
  adults: number
  children: number
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  reservationId: string
}

export type GuestsUpdateManyMutationInput = {
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  attending?: Prisma.BoolFieldUpdateOperationsInput | boolean
  adults?: Prisma.IntFieldUpdateOperationsInput | number
  children?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type GuestsUncheckedUpdateManyInput = {
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  attending?: Prisma.BoolFieldUpdateOperationsInput | boolean
  adults?: Prisma.IntFieldUpdateOperationsInput | number
  children?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reservationId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type GuestsListRelationFilter = {
  every?: Prisma.GuestsWhereInput
  some?: Prisma.GuestsWhereInput
  none?: Prisma.GuestsWhereInput
}

export type GuestsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type GuestsEmailReservationIdCompoundUniqueInput = {
  email: string
  reservationId: string
}

export type GuestsCountOrderByAggregateInput = {
  email?: Prisma.SortOrder
  name?: Prisma.SortOrder
  attending?: Prisma.SortOrder
  adults?: Prisma.SortOrder
  children?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  reservationId?: Prisma.SortOrder
}

export type GuestsAvgOrderByAggregateInput = {
  adults?: Prisma.SortOrder
  children?: Prisma.SortOrder
}

export type GuestsMaxOrderByAggregateInput = {
  email?: Prisma.SortOrder
  name?: Prisma.SortOrder
  attending?: Prisma.SortOrder
  adults?: Prisma.SortOrder
  children?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  reservationId?: Prisma.SortOrder
}

export type GuestsMinOrderByAggregateInput = {
  email?: Prisma.SortOrder
  name?: Prisma.SortOrder
  attending?: Prisma.SortOrder
  adults?: Prisma.SortOrder
  children?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  reservationId?: Prisma.SortOrder
}

export type GuestsSumOrderByAggregateInput = {
  adults?: Prisma.SortOrder
  children?: Prisma.SortOrder
}

export type GuestsCreateNestedManyWithoutReservationInput = {
  create?: Prisma.XOR<Prisma.GuestsCreateWithoutReservationInput, Prisma.GuestsUncheckedCreateWithoutReservationInput> | Prisma.GuestsCreateWithoutReservationInput[] | Prisma.GuestsUncheckedCreateWithoutReservationInput[]
  connectOrCreate?: Prisma.GuestsCreateOrConnectWithoutReservationInput | Prisma.GuestsCreateOrConnectWithoutReservationInput[]
  createMany?: Prisma.GuestsCreateManyReservationInputEnvelope
  connect?: Prisma.GuestsWhereUniqueInput | Prisma.GuestsWhereUniqueInput[]
}

export type GuestsUncheckedCreateNestedManyWithoutReservationInput = {
  create?: Prisma.XOR<Prisma.GuestsCreateWithoutReservationInput, Prisma.GuestsUncheckedCreateWithoutReservationInput> | Prisma.GuestsCreateWithoutReservationInput[] | Prisma.GuestsUncheckedCreateWithoutReservationInput[]
  connectOrCreate?: Prisma.GuestsCreateOrConnectWithoutReservationInput | Prisma.GuestsCreateOrConnectWithoutReservationInput[]
  createMany?: Prisma.GuestsCreateManyReservationInputEnvelope
  connect?: Prisma.GuestsWhereUniqueInput | Prisma.GuestsWhereUniqueInput[]
}

export type GuestsUpdateManyWithoutReservationNestedInput = {
  create?: Prisma.XOR<Prisma.GuestsCreateWithoutReservationInput, Prisma.GuestsUncheckedCreateWithoutReservationInput> | Prisma.GuestsCreateWithoutReservationInput[] | Prisma.GuestsUncheckedCreateWithoutReservationInput[]
  connectOrCreate?: Prisma.GuestsCreateOrConnectWithoutReservationInput | Prisma.GuestsCreateOrConnectWithoutReservationInput[]
  upsert?: Prisma.GuestsUpsertWithWhereUniqueWithoutReservationInput | Prisma.GuestsUpsertWithWhereUniqueWithoutReservationInput[]
  createMany?: Prisma.GuestsCreateManyReservationInputEnvelope
  set?: Prisma.GuestsWhereUniqueInput | Prisma.GuestsWhereUniqueInput[]
  disconnect?: Prisma.GuestsWhereUniqueInput | Prisma.GuestsWhereUniqueInput[]
  delete?: Prisma.GuestsWhereUniqueInput | Prisma.GuestsWhereUniqueInput[]
  connect?: Prisma.GuestsWhereUniqueInput | Prisma.GuestsWhereUniqueInput[]
  update?: Prisma.GuestsUpdateWithWhereUniqueWithoutReservationInput | Prisma.GuestsUpdateWithWhereUniqueWithoutReservationInput[]
  updateMany?: Prisma.GuestsUpdateManyWithWhereWithoutReservationInput | Prisma.GuestsUpdateManyWithWhereWithoutReservationInput[]
  deleteMany?: Prisma.GuestsScalarWhereInput | Prisma.GuestsScalarWhereInput[]
}

export type GuestsUncheckedUpdateManyWithoutReservationNestedInput = {
  create?: Prisma.XOR<Prisma.GuestsCreateWithoutReservationInput, Prisma.GuestsUncheckedCreateWithoutReservationInput> | Prisma.GuestsCreateWithoutReservationInput[] | Prisma.GuestsUncheckedCreateWithoutReservationInput[]
  connectOrCreate?: Prisma.GuestsCreateOrConnectWithoutReservationInput | Prisma.GuestsCreateOrConnectWithoutReservationInput[]
  upsert?: Prisma.GuestsUpsertWithWhereUniqueWithoutReservationInput | Prisma.GuestsUpsertWithWhereUniqueWithoutReservationInput[]
  createMany?: Prisma.GuestsCreateManyReservationInputEnvelope
  set?: Prisma.GuestsWhereUniqueInput | Prisma.GuestsWhereUniqueInput[]
  disconnect?: Prisma.GuestsWhereUniqueInput | Prisma.GuestsWhereUniqueInput[]
  delete?: Prisma.GuestsWhereUniqueInput | Prisma.GuestsWhereUniqueInput[]
  connect?: Prisma.GuestsWhereUniqueInput | Prisma.GuestsWhereUniqueInput[]
  update?: Prisma.GuestsUpdateWithWhereUniqueWithoutReservationInput | Prisma.GuestsUpdateWithWhereUniqueWithoutReservationInput[]
  updateMany?: Prisma.GuestsUpdateManyWithWhereWithoutReservationInput | Prisma.GuestsUpdateManyWithWhereWithoutReservationInput[]
  deleteMany?: Prisma.GuestsScalarWhereInput | Prisma.GuestsScalarWhereInput[]
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type GuestsCreateWithoutReservationInput = {
  email: string
  name: string
  attending: boolean
  adults: number
  children: number
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type GuestsUncheckedCreateWithoutReservationInput = {
  email: string
  name: string
  attending: boolean
  adults: number
  children: number
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type GuestsCreateOrConnectWithoutReservationInput = {
  where: Prisma.GuestsWhereUniqueInput
  create: Prisma.XOR<Prisma.GuestsCreateWithoutReservationInput, Prisma.GuestsUncheckedCreateWithoutReservationInput>
}

export type GuestsCreateManyReservationInputEnvelope = {
  data: Prisma.GuestsCreateManyReservationInput | Prisma.GuestsCreateManyReservationInput[]
}

export type GuestsUpsertWithWhereUniqueWithoutReservationInput = {
  where: Prisma.GuestsWhereUniqueInput
  update: Prisma.XOR<Prisma.GuestsUpdateWithoutReservationInput, Prisma.GuestsUncheckedUpdateWithoutReservationInput>
  create: Prisma.XOR<Prisma.GuestsCreateWithoutReservationInput, Prisma.GuestsUncheckedCreateWithoutReservationInput>
}

export type GuestsUpdateWithWhereUniqueWithoutReservationInput = {
  where: Prisma.GuestsWhereUniqueInput
  data: Prisma.XOR<Prisma.GuestsUpdateWithoutReservationInput, Prisma.GuestsUncheckedUpdateWithoutReservationInput>
}

export type GuestsUpdateManyWithWhereWithoutReservationInput = {
  where: Prisma.GuestsScalarWhereInput
  data: Prisma.XOR<Prisma.GuestsUpdateManyMutationInput, Prisma.GuestsUncheckedUpdateManyWithoutReservationInput>
}

export type GuestsScalarWhereInput = {
  AND?: Prisma.GuestsScalarWhereInput | Prisma.GuestsScalarWhereInput[]
  OR?: Prisma.GuestsScalarWhereInput[]
  NOT?: Prisma.GuestsScalarWhereInput | Prisma.GuestsScalarWhereInput[]
  email?: Prisma.StringFilter<"Guests"> | string
  name?: Prisma.StringFilter<"Guests"> | string
  attending?: Prisma.BoolFilter<"Guests"> | boolean
  adults?: Prisma.IntFilter<"Guests"> | number
  children?: Prisma.IntFilter<"Guests"> | number
  notes?: Prisma.StringNullableFilter<"Guests"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Guests"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Guests"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Guests"> | Date | string | null
  reservationId?: Prisma.StringFilter<"Guests"> | string
}

export type GuestsCreateManyReservationInput = {
  email: string
  name: string
  attending: boolean
  adults: number
  children: number
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type GuestsUpdateWithoutReservationInput = {
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  attending?: Prisma.BoolFieldUpdateOperationsInput | boolean
  adults?: Prisma.IntFieldUpdateOperationsInput | number
  children?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type GuestsUncheckedUpdateWithoutReservationInput = {
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  attending?: Prisma.BoolFieldUpdateOperationsInput | boolean
  adults?: Prisma.IntFieldUpdateOperationsInput | number
  children?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type GuestsUncheckedUpdateManyWithoutReservationInput = {
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  attending?: Prisma.BoolFieldUpdateOperationsInput | boolean
  adults?: Prisma.IntFieldUpdateOperationsInput | number
  children?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type GuestsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  email?: boolean
  name?: boolean
  attending?: boolean
  adults?: boolean
  children?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  reservationId?: boolean
  reservation?: boolean | Prisma.EventSlotDefaultArgs<ExtArgs>
}, ExtArgs["result"]["guests"]>

export type GuestsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  email?: boolean
  name?: boolean
  attending?: boolean
  adults?: boolean
  children?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  reservationId?: boolean
  reservation?: boolean | Prisma.EventSlotDefaultArgs<ExtArgs>
}, ExtArgs["result"]["guests"]>

export type GuestsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  email?: boolean
  name?: boolean
  attending?: boolean
  adults?: boolean
  children?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  reservationId?: boolean
  reservation?: boolean | Prisma.EventSlotDefaultArgs<ExtArgs>
}, ExtArgs["result"]["guests"]>

export type GuestsSelectScalar = {
  email?: boolean
  name?: boolean
  attending?: boolean
  adults?: boolean
  children?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  reservationId?: boolean
}

export type GuestsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"email" | "name" | "attending" | "adults" | "children" | "notes" | "createdAt" | "updatedAt" | "deletedAt" | "reservationId", ExtArgs["result"]["guests"]>
export type GuestsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  reservation?: boolean | Prisma.EventSlotDefaultArgs<ExtArgs>
}
export type GuestsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  reservation?: boolean | Prisma.EventSlotDefaultArgs<ExtArgs>
}
export type GuestsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  reservation?: boolean | Prisma.EventSlotDefaultArgs<ExtArgs>
}

export type $GuestsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Guests"
  objects: {
    reservation: Prisma.$EventSlotPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    email: string
    name: string
    attending: boolean
    adults: number
    children: number
    notes: string | null
    createdAt: Date
    updatedAt: Date
    deletedAt: Date | null
    reservationId: string
  }, ExtArgs["result"]["guests"]>
  composites: {}
}

export type GuestsGetPayload<S extends boolean | null | undefined | GuestsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GuestsPayload, S>

export type GuestsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GuestsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GuestsCountAggregateInputType | true
  }

export interface GuestsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Guests'], meta: { name: 'Guests' } }
  /**
   * Find zero or one Guests that matches the filter.
   * @param {GuestsFindUniqueArgs} args - Arguments to find a Guests
   * @example
   * // Get one Guests
   * const guests = await prisma.guests.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GuestsFindUniqueArgs>(args: Prisma.SelectSubset<T, GuestsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GuestsClient<runtime.Types.Result.GetResult<Prisma.$GuestsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Guests that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GuestsFindUniqueOrThrowArgs} args - Arguments to find a Guests
   * @example
   * // Get one Guests
   * const guests = await prisma.guests.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GuestsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GuestsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GuestsClient<runtime.Types.Result.GetResult<Prisma.$GuestsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Guests that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuestsFindFirstArgs} args - Arguments to find a Guests
   * @example
   * // Get one Guests
   * const guests = await prisma.guests.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GuestsFindFirstArgs>(args?: Prisma.SelectSubset<T, GuestsFindFirstArgs<ExtArgs>>): Prisma.Prisma__GuestsClient<runtime.Types.Result.GetResult<Prisma.$GuestsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Guests that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuestsFindFirstOrThrowArgs} args - Arguments to find a Guests
   * @example
   * // Get one Guests
   * const guests = await prisma.guests.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GuestsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GuestsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GuestsClient<runtime.Types.Result.GetResult<Prisma.$GuestsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Guests that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuestsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Guests
   * const guests = await prisma.guests.findMany()
   * 
   * // Get first 10 Guests
   * const guests = await prisma.guests.findMany({ take: 10 })
   * 
   * // Only select the `email`
   * const guestsWithEmailOnly = await prisma.guests.findMany({ select: { email: true } })
   * 
   */
  findMany<T extends GuestsFindManyArgs>(args?: Prisma.SelectSubset<T, GuestsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GuestsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Guests.
   * @param {GuestsCreateArgs} args - Arguments to create a Guests.
   * @example
   * // Create one Guests
   * const Guests = await prisma.guests.create({
   *   data: {
   *     // ... data to create a Guests
   *   }
   * })
   * 
   */
  create<T extends GuestsCreateArgs>(args: Prisma.SelectSubset<T, GuestsCreateArgs<ExtArgs>>): Prisma.Prisma__GuestsClient<runtime.Types.Result.GetResult<Prisma.$GuestsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Guests.
   * @param {GuestsCreateManyArgs} args - Arguments to create many Guests.
   * @example
   * // Create many Guests
   * const guests = await prisma.guests.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GuestsCreateManyArgs>(args?: Prisma.SelectSubset<T, GuestsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Guests and returns the data saved in the database.
   * @param {GuestsCreateManyAndReturnArgs} args - Arguments to create many Guests.
   * @example
   * // Create many Guests
   * const guests = await prisma.guests.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Guests and only return the `email`
   * const guestsWithEmailOnly = await prisma.guests.createManyAndReturn({
   *   select: { email: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends GuestsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, GuestsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GuestsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Guests.
   * @param {GuestsDeleteArgs} args - Arguments to delete one Guests.
   * @example
   * // Delete one Guests
   * const Guests = await prisma.guests.delete({
   *   where: {
   *     // ... filter to delete one Guests
   *   }
   * })
   * 
   */
  delete<T extends GuestsDeleteArgs>(args: Prisma.SelectSubset<T, GuestsDeleteArgs<ExtArgs>>): Prisma.Prisma__GuestsClient<runtime.Types.Result.GetResult<Prisma.$GuestsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Guests.
   * @param {GuestsUpdateArgs} args - Arguments to update one Guests.
   * @example
   * // Update one Guests
   * const guests = await prisma.guests.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GuestsUpdateArgs>(args: Prisma.SelectSubset<T, GuestsUpdateArgs<ExtArgs>>): Prisma.Prisma__GuestsClient<runtime.Types.Result.GetResult<Prisma.$GuestsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Guests.
   * @param {GuestsDeleteManyArgs} args - Arguments to filter Guests to delete.
   * @example
   * // Delete a few Guests
   * const { count } = await prisma.guests.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GuestsDeleteManyArgs>(args?: Prisma.SelectSubset<T, GuestsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Guests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuestsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Guests
   * const guests = await prisma.guests.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GuestsUpdateManyArgs>(args: Prisma.SelectSubset<T, GuestsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Guests and returns the data updated in the database.
   * @param {GuestsUpdateManyAndReturnArgs} args - Arguments to update many Guests.
   * @example
   * // Update many Guests
   * const guests = await prisma.guests.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Guests and only return the `email`
   * const guestsWithEmailOnly = await prisma.guests.updateManyAndReturn({
   *   select: { email: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends GuestsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, GuestsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GuestsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Guests.
   * @param {GuestsUpsertArgs} args - Arguments to update or create a Guests.
   * @example
   * // Update or create a Guests
   * const guests = await prisma.guests.upsert({
   *   create: {
   *     // ... data to create a Guests
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Guests we want to update
   *   }
   * })
   */
  upsert<T extends GuestsUpsertArgs>(args: Prisma.SelectSubset<T, GuestsUpsertArgs<ExtArgs>>): Prisma.Prisma__GuestsClient<runtime.Types.Result.GetResult<Prisma.$GuestsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Guests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuestsCountArgs} args - Arguments to filter Guests to count.
   * @example
   * // Count the number of Guests
   * const count = await prisma.guests.count({
   *   where: {
   *     // ... the filter for the Guests we want to count
   *   }
   * })
  **/
  count<T extends GuestsCountArgs>(
    args?: Prisma.Subset<T, GuestsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GuestsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Guests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuestsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GuestsAggregateArgs>(args: Prisma.Subset<T, GuestsAggregateArgs>): Prisma.PrismaPromise<GetGuestsAggregateType<T>>

  /**
   * Group by Guests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuestsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GuestsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GuestsGroupByArgs['orderBy'] }
      : { orderBy?: GuestsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GuestsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGuestsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Guests model
 */
readonly fields: GuestsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Guests.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GuestsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  reservation<T extends Prisma.EventSlotDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EventSlotDefaultArgs<ExtArgs>>): Prisma.Prisma__EventSlotClient<runtime.Types.Result.GetResult<Prisma.$EventSlotPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Guests model
 */
export interface GuestsFieldRefs {
  readonly email: Prisma.FieldRef<"Guests", 'String'>
  readonly name: Prisma.FieldRef<"Guests", 'String'>
  readonly attending: Prisma.FieldRef<"Guests", 'Boolean'>
  readonly adults: Prisma.FieldRef<"Guests", 'Int'>
  readonly children: Prisma.FieldRef<"Guests", 'Int'>
  readonly notes: Prisma.FieldRef<"Guests", 'String'>
  readonly createdAt: Prisma.FieldRef<"Guests", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Guests", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"Guests", 'DateTime'>
  readonly reservationId: Prisma.FieldRef<"Guests", 'String'>
}
    

// Custom InputTypes
/**
 * Guests findUnique
 */
export type GuestsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Guests
   */
  select?: Prisma.GuestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Guests
   */
  omit?: Prisma.GuestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuestsInclude<ExtArgs> | null
  /**
   * Filter, which Guests to fetch.
   */
  where: Prisma.GuestsWhereUniqueInput
}

/**
 * Guests findUniqueOrThrow
 */
export type GuestsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Guests
   */
  select?: Prisma.GuestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Guests
   */
  omit?: Prisma.GuestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuestsInclude<ExtArgs> | null
  /**
   * Filter, which Guests to fetch.
   */
  where: Prisma.GuestsWhereUniqueInput
}

/**
 * Guests findFirst
 */
export type GuestsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Guests
   */
  select?: Prisma.GuestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Guests
   */
  omit?: Prisma.GuestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuestsInclude<ExtArgs> | null
  /**
   * Filter, which Guests to fetch.
   */
  where?: Prisma.GuestsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Guests to fetch.
   */
  orderBy?: Prisma.GuestsOrderByWithRelationInput | Prisma.GuestsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Guests.
   */
  cursor?: Prisma.GuestsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Guests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Guests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Guests.
   */
  distinct?: Prisma.GuestsScalarFieldEnum | Prisma.GuestsScalarFieldEnum[]
}

/**
 * Guests findFirstOrThrow
 */
export type GuestsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Guests
   */
  select?: Prisma.GuestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Guests
   */
  omit?: Prisma.GuestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuestsInclude<ExtArgs> | null
  /**
   * Filter, which Guests to fetch.
   */
  where?: Prisma.GuestsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Guests to fetch.
   */
  orderBy?: Prisma.GuestsOrderByWithRelationInput | Prisma.GuestsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Guests.
   */
  cursor?: Prisma.GuestsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Guests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Guests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Guests.
   */
  distinct?: Prisma.GuestsScalarFieldEnum | Prisma.GuestsScalarFieldEnum[]
}

/**
 * Guests findMany
 */
export type GuestsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Guests
   */
  select?: Prisma.GuestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Guests
   */
  omit?: Prisma.GuestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuestsInclude<ExtArgs> | null
  /**
   * Filter, which Guests to fetch.
   */
  where?: Prisma.GuestsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Guests to fetch.
   */
  orderBy?: Prisma.GuestsOrderByWithRelationInput | Prisma.GuestsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Guests.
   */
  cursor?: Prisma.GuestsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Guests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Guests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Guests.
   */
  distinct?: Prisma.GuestsScalarFieldEnum | Prisma.GuestsScalarFieldEnum[]
}

/**
 * Guests create
 */
export type GuestsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Guests
   */
  select?: Prisma.GuestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Guests
   */
  omit?: Prisma.GuestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuestsInclude<ExtArgs> | null
  /**
   * The data needed to create a Guests.
   */
  data: Prisma.XOR<Prisma.GuestsCreateInput, Prisma.GuestsUncheckedCreateInput>
}

/**
 * Guests createMany
 */
export type GuestsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Guests.
   */
  data: Prisma.GuestsCreateManyInput | Prisma.GuestsCreateManyInput[]
}

/**
 * Guests createManyAndReturn
 */
export type GuestsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Guests
   */
  select?: Prisma.GuestsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Guests
   */
  omit?: Prisma.GuestsOmit<ExtArgs> | null
  /**
   * The data used to create many Guests.
   */
  data: Prisma.GuestsCreateManyInput | Prisma.GuestsCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuestsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Guests update
 */
export type GuestsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Guests
   */
  select?: Prisma.GuestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Guests
   */
  omit?: Prisma.GuestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuestsInclude<ExtArgs> | null
  /**
   * The data needed to update a Guests.
   */
  data: Prisma.XOR<Prisma.GuestsUpdateInput, Prisma.GuestsUncheckedUpdateInput>
  /**
   * Choose, which Guests to update.
   */
  where: Prisma.GuestsWhereUniqueInput
}

/**
 * Guests updateMany
 */
export type GuestsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Guests.
   */
  data: Prisma.XOR<Prisma.GuestsUpdateManyMutationInput, Prisma.GuestsUncheckedUpdateManyInput>
  /**
   * Filter which Guests to update
   */
  where?: Prisma.GuestsWhereInput
  /**
   * Limit how many Guests to update.
   */
  limit?: number
}

/**
 * Guests updateManyAndReturn
 */
export type GuestsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Guests
   */
  select?: Prisma.GuestsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Guests
   */
  omit?: Prisma.GuestsOmit<ExtArgs> | null
  /**
   * The data used to update Guests.
   */
  data: Prisma.XOR<Prisma.GuestsUpdateManyMutationInput, Prisma.GuestsUncheckedUpdateManyInput>
  /**
   * Filter which Guests to update
   */
  where?: Prisma.GuestsWhereInput
  /**
   * Limit how many Guests to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuestsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Guests upsert
 */
export type GuestsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Guests
   */
  select?: Prisma.GuestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Guests
   */
  omit?: Prisma.GuestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuestsInclude<ExtArgs> | null
  /**
   * The filter to search for the Guests to update in case it exists.
   */
  where: Prisma.GuestsWhereUniqueInput
  /**
   * In case the Guests found by the `where` argument doesn't exist, create a new Guests with this data.
   */
  create: Prisma.XOR<Prisma.GuestsCreateInput, Prisma.GuestsUncheckedCreateInput>
  /**
   * In case the Guests was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GuestsUpdateInput, Prisma.GuestsUncheckedUpdateInput>
}

/**
 * Guests delete
 */
export type GuestsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Guests
   */
  select?: Prisma.GuestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Guests
   */
  omit?: Prisma.GuestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuestsInclude<ExtArgs> | null
  /**
   * Filter which Guests to delete.
   */
  where: Prisma.GuestsWhereUniqueInput
}

/**
 * Guests deleteMany
 */
export type GuestsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Guests to delete
   */
  where?: Prisma.GuestsWhereInput
  /**
   * Limit how many Guests to delete.
   */
  limit?: number
}

/**
 * Guests without action
 */
export type GuestsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Guests
   */
  select?: Prisma.GuestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Guests
   */
  omit?: Prisma.GuestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuestsInclude<ExtArgs> | null
}
