
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `WishlistClaim` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model WishlistClaim
 * 
 */
export type WishlistClaimModel = runtime.Types.Result.DefaultSelection<Prisma.$WishlistClaimPayload>

export type AggregateWishlistClaim = {
  _count: WishlistClaimCountAggregateOutputType | null
  _avg: WishlistClaimAvgAggregateOutputType | null
  _sum: WishlistClaimSumAggregateOutputType | null
  _min: WishlistClaimMinAggregateOutputType | null
  _max: WishlistClaimMaxAggregateOutputType | null
}

export type WishlistClaimAvgAggregateOutputType = {
  amount: number | null
}

export type WishlistClaimSumAggregateOutputType = {
  amount: number | null
}

export type WishlistClaimMinAggregateOutputType = {
  email: string | null
  wishlistId: string | null
  amount: number | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type WishlistClaimMaxAggregateOutputType = {
  email: string | null
  wishlistId: string | null
  amount: number | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type WishlistClaimCountAggregateOutputType = {
  email: number
  wishlistId: number
  amount: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  _all: number
}


export type WishlistClaimAvgAggregateInputType = {
  amount?: true
}

export type WishlistClaimSumAggregateInputType = {
  amount?: true
}

export type WishlistClaimMinAggregateInputType = {
  email?: true
  wishlistId?: true
  amount?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type WishlistClaimMaxAggregateInputType = {
  email?: true
  wishlistId?: true
  amount?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type WishlistClaimCountAggregateInputType = {
  email?: true
  wishlistId?: true
  amount?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  _all?: true
}

export type WishlistClaimAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WishlistClaim to aggregate.
   */
  where?: Prisma.WishlistClaimWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WishlistClaims to fetch.
   */
  orderBy?: Prisma.WishlistClaimOrderByWithRelationInput | Prisma.WishlistClaimOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.WishlistClaimWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WishlistClaims from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WishlistClaims.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned WishlistClaims
  **/
  _count?: true | WishlistClaimCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: WishlistClaimAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: WishlistClaimSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WishlistClaimMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WishlistClaimMaxAggregateInputType
}

export type GetWishlistClaimAggregateType<T extends WishlistClaimAggregateArgs> = {
      [P in keyof T & keyof AggregateWishlistClaim]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWishlistClaim[P]>
    : Prisma.GetScalarType<T[P], AggregateWishlistClaim[P]>
}




export type WishlistClaimGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WishlistClaimWhereInput
  orderBy?: Prisma.WishlistClaimOrderByWithAggregationInput | Prisma.WishlistClaimOrderByWithAggregationInput[]
  by: Prisma.WishlistClaimScalarFieldEnum[] | Prisma.WishlistClaimScalarFieldEnum
  having?: Prisma.WishlistClaimScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WishlistClaimCountAggregateInputType | true
  _avg?: WishlistClaimAvgAggregateInputType
  _sum?: WishlistClaimSumAggregateInputType
  _min?: WishlistClaimMinAggregateInputType
  _max?: WishlistClaimMaxAggregateInputType
}

export type WishlistClaimGroupByOutputType = {
  email: string
  wishlistId: string
  amount: number
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  _count: WishlistClaimCountAggregateOutputType | null
  _avg: WishlistClaimAvgAggregateOutputType | null
  _sum: WishlistClaimSumAggregateOutputType | null
  _min: WishlistClaimMinAggregateOutputType | null
  _max: WishlistClaimMaxAggregateOutputType | null
}

export type GetWishlistClaimGroupByPayload<T extends WishlistClaimGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WishlistClaimGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WishlistClaimGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WishlistClaimGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WishlistClaimGroupByOutputType[P]>
      }
    >
  >



export type WishlistClaimWhereInput = {
  AND?: Prisma.WishlistClaimWhereInput | Prisma.WishlistClaimWhereInput[]
  OR?: Prisma.WishlistClaimWhereInput[]
  NOT?: Prisma.WishlistClaimWhereInput | Prisma.WishlistClaimWhereInput[]
  email?: Prisma.StringFilter<"WishlistClaim"> | string
  wishlistId?: Prisma.StringFilter<"WishlistClaim"> | string
  amount?: Prisma.IntFilter<"WishlistClaim"> | number
  createdAt?: Prisma.DateTimeFilter<"WishlistClaim"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"WishlistClaim"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"WishlistClaim"> | Date | string | null
  wishlist?: Prisma.XOR<Prisma.WishlistScalarRelationFilter, Prisma.WishlistWhereInput>
}

export type WishlistClaimOrderByWithRelationInput = {
  email?: Prisma.SortOrder
  wishlistId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  wishlist?: Prisma.WishlistOrderByWithRelationInput
}

export type WishlistClaimWhereUniqueInput = Prisma.AtLeast<{
  email_wishlistId?: Prisma.WishlistClaimEmailWishlistIdCompoundUniqueInput
  AND?: Prisma.WishlistClaimWhereInput | Prisma.WishlistClaimWhereInput[]
  OR?: Prisma.WishlistClaimWhereInput[]
  NOT?: Prisma.WishlistClaimWhereInput | Prisma.WishlistClaimWhereInput[]
  email?: Prisma.StringFilter<"WishlistClaim"> | string
  wishlistId?: Prisma.StringFilter<"WishlistClaim"> | string
  amount?: Prisma.IntFilter<"WishlistClaim"> | number
  createdAt?: Prisma.DateTimeFilter<"WishlistClaim"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"WishlistClaim"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"WishlistClaim"> | Date | string | null
  wishlist?: Prisma.XOR<Prisma.WishlistScalarRelationFilter, Prisma.WishlistWhereInput>
}, "email_wishlistId">

export type WishlistClaimOrderByWithAggregationInput = {
  email?: Prisma.SortOrder
  wishlistId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.WishlistClaimCountOrderByAggregateInput
  _avg?: Prisma.WishlistClaimAvgOrderByAggregateInput
  _max?: Prisma.WishlistClaimMaxOrderByAggregateInput
  _min?: Prisma.WishlistClaimMinOrderByAggregateInput
  _sum?: Prisma.WishlistClaimSumOrderByAggregateInput
}

export type WishlistClaimScalarWhereWithAggregatesInput = {
  AND?: Prisma.WishlistClaimScalarWhereWithAggregatesInput | Prisma.WishlistClaimScalarWhereWithAggregatesInput[]
  OR?: Prisma.WishlistClaimScalarWhereWithAggregatesInput[]
  NOT?: Prisma.WishlistClaimScalarWhereWithAggregatesInput | Prisma.WishlistClaimScalarWhereWithAggregatesInput[]
  email?: Prisma.StringWithAggregatesFilter<"WishlistClaim"> | string
  wishlistId?: Prisma.StringWithAggregatesFilter<"WishlistClaim"> | string
  amount?: Prisma.IntWithAggregatesFilter<"WishlistClaim"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"WishlistClaim"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"WishlistClaim"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"WishlistClaim"> | Date | string | null
}

export type WishlistClaimCreateInput = {
  email: string
  amount: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  wishlist: Prisma.WishlistCreateNestedOneWithoutClaimsInput
}

export type WishlistClaimUncheckedCreateInput = {
  email: string
  wishlistId: string
  amount: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type WishlistClaimUpdateInput = {
  email?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  wishlist?: Prisma.WishlistUpdateOneRequiredWithoutClaimsNestedInput
}

export type WishlistClaimUncheckedUpdateInput = {
  email?: Prisma.StringFieldUpdateOperationsInput | string
  wishlistId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type WishlistClaimCreateManyInput = {
  email: string
  wishlistId: string
  amount: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type WishlistClaimUpdateManyMutationInput = {
  email?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type WishlistClaimUncheckedUpdateManyInput = {
  email?: Prisma.StringFieldUpdateOperationsInput | string
  wishlistId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type WishlistClaimListRelationFilter = {
  every?: Prisma.WishlistClaimWhereInput
  some?: Prisma.WishlistClaimWhereInput
  none?: Prisma.WishlistClaimWhereInput
}

export type WishlistClaimOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type WishlistClaimEmailWishlistIdCompoundUniqueInput = {
  email: string
  wishlistId: string
}

export type WishlistClaimCountOrderByAggregateInput = {
  email?: Prisma.SortOrder
  wishlistId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type WishlistClaimAvgOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type WishlistClaimMaxOrderByAggregateInput = {
  email?: Prisma.SortOrder
  wishlistId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type WishlistClaimMinOrderByAggregateInput = {
  email?: Prisma.SortOrder
  wishlistId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type WishlistClaimSumOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type WishlistClaimCreateNestedManyWithoutWishlistInput = {
  create?: Prisma.XOR<Prisma.WishlistClaimCreateWithoutWishlistInput, Prisma.WishlistClaimUncheckedCreateWithoutWishlistInput> | Prisma.WishlistClaimCreateWithoutWishlistInput[] | Prisma.WishlistClaimUncheckedCreateWithoutWishlistInput[]
  connectOrCreate?: Prisma.WishlistClaimCreateOrConnectWithoutWishlistInput | Prisma.WishlistClaimCreateOrConnectWithoutWishlistInput[]
  createMany?: Prisma.WishlistClaimCreateManyWishlistInputEnvelope
  connect?: Prisma.WishlistClaimWhereUniqueInput | Prisma.WishlistClaimWhereUniqueInput[]
}

export type WishlistClaimUncheckedCreateNestedManyWithoutWishlistInput = {
  create?: Prisma.XOR<Prisma.WishlistClaimCreateWithoutWishlistInput, Prisma.WishlistClaimUncheckedCreateWithoutWishlistInput> | Prisma.WishlistClaimCreateWithoutWishlistInput[] | Prisma.WishlistClaimUncheckedCreateWithoutWishlistInput[]
  connectOrCreate?: Prisma.WishlistClaimCreateOrConnectWithoutWishlistInput | Prisma.WishlistClaimCreateOrConnectWithoutWishlistInput[]
  createMany?: Prisma.WishlistClaimCreateManyWishlistInputEnvelope
  connect?: Prisma.WishlistClaimWhereUniqueInput | Prisma.WishlistClaimWhereUniqueInput[]
}

export type WishlistClaimUpdateManyWithoutWishlistNestedInput = {
  create?: Prisma.XOR<Prisma.WishlistClaimCreateWithoutWishlistInput, Prisma.WishlistClaimUncheckedCreateWithoutWishlistInput> | Prisma.WishlistClaimCreateWithoutWishlistInput[] | Prisma.WishlistClaimUncheckedCreateWithoutWishlistInput[]
  connectOrCreate?: Prisma.WishlistClaimCreateOrConnectWithoutWishlistInput | Prisma.WishlistClaimCreateOrConnectWithoutWishlistInput[]
  upsert?: Prisma.WishlistClaimUpsertWithWhereUniqueWithoutWishlistInput | Prisma.WishlistClaimUpsertWithWhereUniqueWithoutWishlistInput[]
  createMany?: Prisma.WishlistClaimCreateManyWishlistInputEnvelope
  set?: Prisma.WishlistClaimWhereUniqueInput | Prisma.WishlistClaimWhereUniqueInput[]
  disconnect?: Prisma.WishlistClaimWhereUniqueInput | Prisma.WishlistClaimWhereUniqueInput[]
  delete?: Prisma.WishlistClaimWhereUniqueInput | Prisma.WishlistClaimWhereUniqueInput[]
  connect?: Prisma.WishlistClaimWhereUniqueInput | Prisma.WishlistClaimWhereUniqueInput[]
  update?: Prisma.WishlistClaimUpdateWithWhereUniqueWithoutWishlistInput | Prisma.WishlistClaimUpdateWithWhereUniqueWithoutWishlistInput[]
  updateMany?: Prisma.WishlistClaimUpdateManyWithWhereWithoutWishlistInput | Prisma.WishlistClaimUpdateManyWithWhereWithoutWishlistInput[]
  deleteMany?: Prisma.WishlistClaimScalarWhereInput | Prisma.WishlistClaimScalarWhereInput[]
}

export type WishlistClaimUncheckedUpdateManyWithoutWishlistNestedInput = {
  create?: Prisma.XOR<Prisma.WishlistClaimCreateWithoutWishlistInput, Prisma.WishlistClaimUncheckedCreateWithoutWishlistInput> | Prisma.WishlistClaimCreateWithoutWishlistInput[] | Prisma.WishlistClaimUncheckedCreateWithoutWishlistInput[]
  connectOrCreate?: Prisma.WishlistClaimCreateOrConnectWithoutWishlistInput | Prisma.WishlistClaimCreateOrConnectWithoutWishlistInput[]
  upsert?: Prisma.WishlistClaimUpsertWithWhereUniqueWithoutWishlistInput | Prisma.WishlistClaimUpsertWithWhereUniqueWithoutWishlistInput[]
  createMany?: Prisma.WishlistClaimCreateManyWishlistInputEnvelope
  set?: Prisma.WishlistClaimWhereUniqueInput | Prisma.WishlistClaimWhereUniqueInput[]
  disconnect?: Prisma.WishlistClaimWhereUniqueInput | Prisma.WishlistClaimWhereUniqueInput[]
  delete?: Prisma.WishlistClaimWhereUniqueInput | Prisma.WishlistClaimWhereUniqueInput[]
  connect?: Prisma.WishlistClaimWhereUniqueInput | Prisma.WishlistClaimWhereUniqueInput[]
  update?: Prisma.WishlistClaimUpdateWithWhereUniqueWithoutWishlistInput | Prisma.WishlistClaimUpdateWithWhereUniqueWithoutWishlistInput[]
  updateMany?: Prisma.WishlistClaimUpdateManyWithWhereWithoutWishlistInput | Prisma.WishlistClaimUpdateManyWithWhereWithoutWishlistInput[]
  deleteMany?: Prisma.WishlistClaimScalarWhereInput | Prisma.WishlistClaimScalarWhereInput[]
}

export type WishlistClaimCreateWithoutWishlistInput = {
  email: string
  amount: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type WishlistClaimUncheckedCreateWithoutWishlistInput = {
  email: string
  amount: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type WishlistClaimCreateOrConnectWithoutWishlistInput = {
  where: Prisma.WishlistClaimWhereUniqueInput
  create: Prisma.XOR<Prisma.WishlistClaimCreateWithoutWishlistInput, Prisma.WishlistClaimUncheckedCreateWithoutWishlistInput>
}

export type WishlistClaimCreateManyWishlistInputEnvelope = {
  data: Prisma.WishlistClaimCreateManyWishlistInput | Prisma.WishlistClaimCreateManyWishlistInput[]
}

export type WishlistClaimUpsertWithWhereUniqueWithoutWishlistInput = {
  where: Prisma.WishlistClaimWhereUniqueInput
  update: Prisma.XOR<Prisma.WishlistClaimUpdateWithoutWishlistInput, Prisma.WishlistClaimUncheckedUpdateWithoutWishlistInput>
  create: Prisma.XOR<Prisma.WishlistClaimCreateWithoutWishlistInput, Prisma.WishlistClaimUncheckedCreateWithoutWishlistInput>
}

export type WishlistClaimUpdateWithWhereUniqueWithoutWishlistInput = {
  where: Prisma.WishlistClaimWhereUniqueInput
  data: Prisma.XOR<Prisma.WishlistClaimUpdateWithoutWishlistInput, Prisma.WishlistClaimUncheckedUpdateWithoutWishlistInput>
}

export type WishlistClaimUpdateManyWithWhereWithoutWishlistInput = {
  where: Prisma.WishlistClaimScalarWhereInput
  data: Prisma.XOR<Prisma.WishlistClaimUpdateManyMutationInput, Prisma.WishlistClaimUncheckedUpdateManyWithoutWishlistInput>
}

export type WishlistClaimScalarWhereInput = {
  AND?: Prisma.WishlistClaimScalarWhereInput | Prisma.WishlistClaimScalarWhereInput[]
  OR?: Prisma.WishlistClaimScalarWhereInput[]
  NOT?: Prisma.WishlistClaimScalarWhereInput | Prisma.WishlistClaimScalarWhereInput[]
  email?: Prisma.StringFilter<"WishlistClaim"> | string
  wishlistId?: Prisma.StringFilter<"WishlistClaim"> | string
  amount?: Prisma.IntFilter<"WishlistClaim"> | number
  createdAt?: Prisma.DateTimeFilter<"WishlistClaim"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"WishlistClaim"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"WishlistClaim"> | Date | string | null
}

export type WishlistClaimCreateManyWishlistInput = {
  email: string
  amount: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type WishlistClaimUpdateWithoutWishlistInput = {
  email?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type WishlistClaimUncheckedUpdateWithoutWishlistInput = {
  email?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type WishlistClaimUncheckedUpdateManyWithoutWishlistInput = {
  email?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type WishlistClaimSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  email?: boolean
  wishlistId?: boolean
  amount?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  wishlist?: boolean | Prisma.WishlistDefaultArgs<ExtArgs>
}, ExtArgs["result"]["wishlistClaim"]>

export type WishlistClaimSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  email?: boolean
  wishlistId?: boolean
  amount?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  wishlist?: boolean | Prisma.WishlistDefaultArgs<ExtArgs>
}, ExtArgs["result"]["wishlistClaim"]>

export type WishlistClaimSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  email?: boolean
  wishlistId?: boolean
  amount?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  wishlist?: boolean | Prisma.WishlistDefaultArgs<ExtArgs>
}, ExtArgs["result"]["wishlistClaim"]>

export type WishlistClaimSelectScalar = {
  email?: boolean
  wishlistId?: boolean
  amount?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}

export type WishlistClaimOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"email" | "wishlistId" | "amount" | "createdAt" | "updatedAt" | "deletedAt", ExtArgs["result"]["wishlistClaim"]>
export type WishlistClaimInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  wishlist?: boolean | Prisma.WishlistDefaultArgs<ExtArgs>
}
export type WishlistClaimIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  wishlist?: boolean | Prisma.WishlistDefaultArgs<ExtArgs>
}
export type WishlistClaimIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  wishlist?: boolean | Prisma.WishlistDefaultArgs<ExtArgs>
}

export type $WishlistClaimPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "WishlistClaim"
  objects: {
    wishlist: Prisma.$WishlistPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    email: string
    wishlistId: string
    amount: number
    createdAt: Date
    updatedAt: Date
    deletedAt: Date | null
  }, ExtArgs["result"]["wishlistClaim"]>
  composites: {}
}

export type WishlistClaimGetPayload<S extends boolean | null | undefined | WishlistClaimDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WishlistClaimPayload, S>

export type WishlistClaimCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<WishlistClaimFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WishlistClaimCountAggregateInputType | true
  }

export interface WishlistClaimDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['WishlistClaim'], meta: { name: 'WishlistClaim' } }
  /**
   * Find zero or one WishlistClaim that matches the filter.
   * @param {WishlistClaimFindUniqueArgs} args - Arguments to find a WishlistClaim
   * @example
   * // Get one WishlistClaim
   * const wishlistClaim = await prisma.wishlistClaim.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WishlistClaimFindUniqueArgs>(args: Prisma.SelectSubset<T, WishlistClaimFindUniqueArgs<ExtArgs>>): Prisma.Prisma__WishlistClaimClient<runtime.Types.Result.GetResult<Prisma.$WishlistClaimPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one WishlistClaim that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WishlistClaimFindUniqueOrThrowArgs} args - Arguments to find a WishlistClaim
   * @example
   * // Get one WishlistClaim
   * const wishlistClaim = await prisma.wishlistClaim.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WishlistClaimFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, WishlistClaimFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__WishlistClaimClient<runtime.Types.Result.GetResult<Prisma.$WishlistClaimPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WishlistClaim that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WishlistClaimFindFirstArgs} args - Arguments to find a WishlistClaim
   * @example
   * // Get one WishlistClaim
   * const wishlistClaim = await prisma.wishlistClaim.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WishlistClaimFindFirstArgs>(args?: Prisma.SelectSubset<T, WishlistClaimFindFirstArgs<ExtArgs>>): Prisma.Prisma__WishlistClaimClient<runtime.Types.Result.GetResult<Prisma.$WishlistClaimPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WishlistClaim that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WishlistClaimFindFirstOrThrowArgs} args - Arguments to find a WishlistClaim
   * @example
   * // Get one WishlistClaim
   * const wishlistClaim = await prisma.wishlistClaim.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WishlistClaimFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, WishlistClaimFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__WishlistClaimClient<runtime.Types.Result.GetResult<Prisma.$WishlistClaimPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more WishlistClaims that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WishlistClaimFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all WishlistClaims
   * const wishlistClaims = await prisma.wishlistClaim.findMany()
   * 
   * // Get first 10 WishlistClaims
   * const wishlistClaims = await prisma.wishlistClaim.findMany({ take: 10 })
   * 
   * // Only select the `email`
   * const wishlistClaimWithEmailOnly = await prisma.wishlistClaim.findMany({ select: { email: true } })
   * 
   */
  findMany<T extends WishlistClaimFindManyArgs>(args?: Prisma.SelectSubset<T, WishlistClaimFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WishlistClaimPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a WishlistClaim.
   * @param {WishlistClaimCreateArgs} args - Arguments to create a WishlistClaim.
   * @example
   * // Create one WishlistClaim
   * const WishlistClaim = await prisma.wishlistClaim.create({
   *   data: {
   *     // ... data to create a WishlistClaim
   *   }
   * })
   * 
   */
  create<T extends WishlistClaimCreateArgs>(args: Prisma.SelectSubset<T, WishlistClaimCreateArgs<ExtArgs>>): Prisma.Prisma__WishlistClaimClient<runtime.Types.Result.GetResult<Prisma.$WishlistClaimPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many WishlistClaims.
   * @param {WishlistClaimCreateManyArgs} args - Arguments to create many WishlistClaims.
   * @example
   * // Create many WishlistClaims
   * const wishlistClaim = await prisma.wishlistClaim.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends WishlistClaimCreateManyArgs>(args?: Prisma.SelectSubset<T, WishlistClaimCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many WishlistClaims and returns the data saved in the database.
   * @param {WishlistClaimCreateManyAndReturnArgs} args - Arguments to create many WishlistClaims.
   * @example
   * // Create many WishlistClaims
   * const wishlistClaim = await prisma.wishlistClaim.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many WishlistClaims and only return the `email`
   * const wishlistClaimWithEmailOnly = await prisma.wishlistClaim.createManyAndReturn({
   *   select: { email: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends WishlistClaimCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, WishlistClaimCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WishlistClaimPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a WishlistClaim.
   * @param {WishlistClaimDeleteArgs} args - Arguments to delete one WishlistClaim.
   * @example
   * // Delete one WishlistClaim
   * const WishlistClaim = await prisma.wishlistClaim.delete({
   *   where: {
   *     // ... filter to delete one WishlistClaim
   *   }
   * })
   * 
   */
  delete<T extends WishlistClaimDeleteArgs>(args: Prisma.SelectSubset<T, WishlistClaimDeleteArgs<ExtArgs>>): Prisma.Prisma__WishlistClaimClient<runtime.Types.Result.GetResult<Prisma.$WishlistClaimPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one WishlistClaim.
   * @param {WishlistClaimUpdateArgs} args - Arguments to update one WishlistClaim.
   * @example
   * // Update one WishlistClaim
   * const wishlistClaim = await prisma.wishlistClaim.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends WishlistClaimUpdateArgs>(args: Prisma.SelectSubset<T, WishlistClaimUpdateArgs<ExtArgs>>): Prisma.Prisma__WishlistClaimClient<runtime.Types.Result.GetResult<Prisma.$WishlistClaimPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more WishlistClaims.
   * @param {WishlistClaimDeleteManyArgs} args - Arguments to filter WishlistClaims to delete.
   * @example
   * // Delete a few WishlistClaims
   * const { count } = await prisma.wishlistClaim.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends WishlistClaimDeleteManyArgs>(args?: Prisma.SelectSubset<T, WishlistClaimDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WishlistClaims.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WishlistClaimUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many WishlistClaims
   * const wishlistClaim = await prisma.wishlistClaim.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends WishlistClaimUpdateManyArgs>(args: Prisma.SelectSubset<T, WishlistClaimUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WishlistClaims and returns the data updated in the database.
   * @param {WishlistClaimUpdateManyAndReturnArgs} args - Arguments to update many WishlistClaims.
   * @example
   * // Update many WishlistClaims
   * const wishlistClaim = await prisma.wishlistClaim.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more WishlistClaims and only return the `email`
   * const wishlistClaimWithEmailOnly = await prisma.wishlistClaim.updateManyAndReturn({
   *   select: { email: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends WishlistClaimUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, WishlistClaimUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WishlistClaimPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one WishlistClaim.
   * @param {WishlistClaimUpsertArgs} args - Arguments to update or create a WishlistClaim.
   * @example
   * // Update or create a WishlistClaim
   * const wishlistClaim = await prisma.wishlistClaim.upsert({
   *   create: {
   *     // ... data to create a WishlistClaim
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the WishlistClaim we want to update
   *   }
   * })
   */
  upsert<T extends WishlistClaimUpsertArgs>(args: Prisma.SelectSubset<T, WishlistClaimUpsertArgs<ExtArgs>>): Prisma.Prisma__WishlistClaimClient<runtime.Types.Result.GetResult<Prisma.$WishlistClaimPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of WishlistClaims.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WishlistClaimCountArgs} args - Arguments to filter WishlistClaims to count.
   * @example
   * // Count the number of WishlistClaims
   * const count = await prisma.wishlistClaim.count({
   *   where: {
   *     // ... the filter for the WishlistClaims we want to count
   *   }
   * })
  **/
  count<T extends WishlistClaimCountArgs>(
    args?: Prisma.Subset<T, WishlistClaimCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WishlistClaimCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a WishlistClaim.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WishlistClaimAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WishlistClaimAggregateArgs>(args: Prisma.Subset<T, WishlistClaimAggregateArgs>): Prisma.PrismaPromise<GetWishlistClaimAggregateType<T>>

  /**
   * Group by WishlistClaim.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WishlistClaimGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends WishlistClaimGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WishlistClaimGroupByArgs['orderBy'] }
      : { orderBy?: WishlistClaimGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, WishlistClaimGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWishlistClaimGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the WishlistClaim model
 */
readonly fields: WishlistClaimFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for WishlistClaim.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WishlistClaimClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  wishlist<T extends Prisma.WishlistDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WishlistDefaultArgs<ExtArgs>>): Prisma.Prisma__WishlistClient<runtime.Types.Result.GetResult<Prisma.$WishlistPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the WishlistClaim model
 */
export interface WishlistClaimFieldRefs {
  readonly email: Prisma.FieldRef<"WishlistClaim", 'String'>
  readonly wishlistId: Prisma.FieldRef<"WishlistClaim", 'String'>
  readonly amount: Prisma.FieldRef<"WishlistClaim", 'Int'>
  readonly createdAt: Prisma.FieldRef<"WishlistClaim", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"WishlistClaim", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"WishlistClaim", 'DateTime'>
}
    

// Custom InputTypes
/**
 * WishlistClaim findUnique
 */
export type WishlistClaimFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WishlistClaim
   */
  select?: Prisma.WishlistClaimSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WishlistClaim
   */
  omit?: Prisma.WishlistClaimOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WishlistClaimInclude<ExtArgs> | null
  /**
   * Filter, which WishlistClaim to fetch.
   */
  where: Prisma.WishlistClaimWhereUniqueInput
}

/**
 * WishlistClaim findUniqueOrThrow
 */
export type WishlistClaimFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WishlistClaim
   */
  select?: Prisma.WishlistClaimSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WishlistClaim
   */
  omit?: Prisma.WishlistClaimOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WishlistClaimInclude<ExtArgs> | null
  /**
   * Filter, which WishlistClaim to fetch.
   */
  where: Prisma.WishlistClaimWhereUniqueInput
}

/**
 * WishlistClaim findFirst
 */
export type WishlistClaimFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WishlistClaim
   */
  select?: Prisma.WishlistClaimSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WishlistClaim
   */
  omit?: Prisma.WishlistClaimOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WishlistClaimInclude<ExtArgs> | null
  /**
   * Filter, which WishlistClaim to fetch.
   */
  where?: Prisma.WishlistClaimWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WishlistClaims to fetch.
   */
  orderBy?: Prisma.WishlistClaimOrderByWithRelationInput | Prisma.WishlistClaimOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WishlistClaims.
   */
  cursor?: Prisma.WishlistClaimWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WishlistClaims from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WishlistClaims.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WishlistClaims.
   */
  distinct?: Prisma.WishlistClaimScalarFieldEnum | Prisma.WishlistClaimScalarFieldEnum[]
}

/**
 * WishlistClaim findFirstOrThrow
 */
export type WishlistClaimFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WishlistClaim
   */
  select?: Prisma.WishlistClaimSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WishlistClaim
   */
  omit?: Prisma.WishlistClaimOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WishlistClaimInclude<ExtArgs> | null
  /**
   * Filter, which WishlistClaim to fetch.
   */
  where?: Prisma.WishlistClaimWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WishlistClaims to fetch.
   */
  orderBy?: Prisma.WishlistClaimOrderByWithRelationInput | Prisma.WishlistClaimOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WishlistClaims.
   */
  cursor?: Prisma.WishlistClaimWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WishlistClaims from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WishlistClaims.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WishlistClaims.
   */
  distinct?: Prisma.WishlistClaimScalarFieldEnum | Prisma.WishlistClaimScalarFieldEnum[]
}

/**
 * WishlistClaim findMany
 */
export type WishlistClaimFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WishlistClaim
   */
  select?: Prisma.WishlistClaimSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WishlistClaim
   */
  omit?: Prisma.WishlistClaimOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WishlistClaimInclude<ExtArgs> | null
  /**
   * Filter, which WishlistClaims to fetch.
   */
  where?: Prisma.WishlistClaimWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WishlistClaims to fetch.
   */
  orderBy?: Prisma.WishlistClaimOrderByWithRelationInput | Prisma.WishlistClaimOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing WishlistClaims.
   */
  cursor?: Prisma.WishlistClaimWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WishlistClaims from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WishlistClaims.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WishlistClaims.
   */
  distinct?: Prisma.WishlistClaimScalarFieldEnum | Prisma.WishlistClaimScalarFieldEnum[]
}

/**
 * WishlistClaim create
 */
export type WishlistClaimCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WishlistClaim
   */
  select?: Prisma.WishlistClaimSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WishlistClaim
   */
  omit?: Prisma.WishlistClaimOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WishlistClaimInclude<ExtArgs> | null
  /**
   * The data needed to create a WishlistClaim.
   */
  data: Prisma.XOR<Prisma.WishlistClaimCreateInput, Prisma.WishlistClaimUncheckedCreateInput>
}

/**
 * WishlistClaim createMany
 */
export type WishlistClaimCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many WishlistClaims.
   */
  data: Prisma.WishlistClaimCreateManyInput | Prisma.WishlistClaimCreateManyInput[]
}

/**
 * WishlistClaim createManyAndReturn
 */
export type WishlistClaimCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WishlistClaim
   */
  select?: Prisma.WishlistClaimSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WishlistClaim
   */
  omit?: Prisma.WishlistClaimOmit<ExtArgs> | null
  /**
   * The data used to create many WishlistClaims.
   */
  data: Prisma.WishlistClaimCreateManyInput | Prisma.WishlistClaimCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WishlistClaimIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * WishlistClaim update
 */
export type WishlistClaimUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WishlistClaim
   */
  select?: Prisma.WishlistClaimSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WishlistClaim
   */
  omit?: Prisma.WishlistClaimOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WishlistClaimInclude<ExtArgs> | null
  /**
   * The data needed to update a WishlistClaim.
   */
  data: Prisma.XOR<Prisma.WishlistClaimUpdateInput, Prisma.WishlistClaimUncheckedUpdateInput>
  /**
   * Choose, which WishlistClaim to update.
   */
  where: Prisma.WishlistClaimWhereUniqueInput
}

/**
 * WishlistClaim updateMany
 */
export type WishlistClaimUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update WishlistClaims.
   */
  data: Prisma.XOR<Prisma.WishlistClaimUpdateManyMutationInput, Prisma.WishlistClaimUncheckedUpdateManyInput>
  /**
   * Filter which WishlistClaims to update
   */
  where?: Prisma.WishlistClaimWhereInput
  /**
   * Limit how many WishlistClaims to update.
   */
  limit?: number
}

/**
 * WishlistClaim updateManyAndReturn
 */
export type WishlistClaimUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WishlistClaim
   */
  select?: Prisma.WishlistClaimSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WishlistClaim
   */
  omit?: Prisma.WishlistClaimOmit<ExtArgs> | null
  /**
   * The data used to update WishlistClaims.
   */
  data: Prisma.XOR<Prisma.WishlistClaimUpdateManyMutationInput, Prisma.WishlistClaimUncheckedUpdateManyInput>
  /**
   * Filter which WishlistClaims to update
   */
  where?: Prisma.WishlistClaimWhereInput
  /**
   * Limit how many WishlistClaims to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WishlistClaimIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * WishlistClaim upsert
 */
export type WishlistClaimUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WishlistClaim
   */
  select?: Prisma.WishlistClaimSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WishlistClaim
   */
  omit?: Prisma.WishlistClaimOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WishlistClaimInclude<ExtArgs> | null
  /**
   * The filter to search for the WishlistClaim to update in case it exists.
   */
  where: Prisma.WishlistClaimWhereUniqueInput
  /**
   * In case the WishlistClaim found by the `where` argument doesn't exist, create a new WishlistClaim with this data.
   */
  create: Prisma.XOR<Prisma.WishlistClaimCreateInput, Prisma.WishlistClaimUncheckedCreateInput>
  /**
   * In case the WishlistClaim was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WishlistClaimUpdateInput, Prisma.WishlistClaimUncheckedUpdateInput>
}

/**
 * WishlistClaim delete
 */
export type WishlistClaimDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WishlistClaim
   */
  select?: Prisma.WishlistClaimSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WishlistClaim
   */
  omit?: Prisma.WishlistClaimOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WishlistClaimInclude<ExtArgs> | null
  /**
   * Filter which WishlistClaim to delete.
   */
  where: Prisma.WishlistClaimWhereUniqueInput
}

/**
 * WishlistClaim deleteMany
 */
export type WishlistClaimDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WishlistClaims to delete
   */
  where?: Prisma.WishlistClaimWhereInput
  /**
   * Limit how many WishlistClaims to delete.
   */
  limit?: number
}

/**
 * WishlistClaim without action
 */
export type WishlistClaimDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WishlistClaim
   */
  select?: Prisma.WishlistClaimSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WishlistClaim
   */
  omit?: Prisma.WishlistClaimOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WishlistClaimInclude<ExtArgs> | null
}
